/**
 * generated by Xtext 2.19.0
 */
package org.xtext.example.mydsl.iDSL.impl;

import java.util.Collection;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.eclipse.emf.ecore.util.EDataTypeEList;

import org.xtext.example.mydsl.iDSL.BarType;
import org.xtext.example.mydsl.iDSL.Barchart;
import org.xtext.example.mydsl.iDSL.Color;
import org.xtext.example.mydsl.iDSL.IDSLPackage;
import org.xtext.example.mydsl.iDSL.LegendStyle;
import org.xtext.example.mydsl.iDSL.ShowOptionsOff;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Barchart</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.iDSL.impl.BarchartImpl#getName <em>Name</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.iDSL.impl.BarchartImpl#getColor <em>Color</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.iDSL.impl.BarchartImpl#getColors <em>Colors</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.iDSL.impl.BarchartImpl#getBardata <em>Bardata</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.iDSL.impl.BarchartImpl#getGridscale <em>Gridscale</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.iDSL.impl.BarchartImpl#getLegendstyle <em>Legendstyle</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.iDSL.impl.BarchartImpl#getPadding <em>Padding</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.iDSL.impl.BarchartImpl#getPosition <em>Position</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.iDSL.impl.BarchartImpl#getShowgrid <em>Showgrid</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.iDSL.impl.BarchartImpl#getShowlegend <em>Showlegend</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.iDSL.impl.BarchartImpl#getShowtitle <em>Showtitle</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.iDSL.impl.BarchartImpl#getSize <em>Size</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.iDSL.impl.BarchartImpl#getTitle <em>Title</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.iDSL.impl.BarchartImpl#getType <em>Type</em>}</li>
 * </ul>
 *
 * @generated
 */
public class BarchartImpl extends MinimalEObjectImpl.Container implements Barchart
{
  /**
   * The default value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected static final String NAME_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected String name = NAME_EDEFAULT;

  /**
   * The cached value of the '{@link #getColor() <em>Color</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getColor()
   * @generated
   * @ordered
   */
  protected Color color;

  /**
   * The default value of the '{@link #getColors() <em>Colors</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getColors()
   * @generated
   * @ordered
   */
  protected static final String COLORS_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getColors() <em>Colors</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getColors()
   * @generated
   * @ordered
   */
  protected String colors = COLORS_EDEFAULT;

  /**
   * The cached value of the '{@link #getBardata() <em>Bardata</em>}' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getBardata()
   * @generated
   * @ordered
   */
  protected EList<String> bardata;

  /**
   * The default value of the '{@link #getGridscale() <em>Gridscale</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getGridscale()
   * @generated
   * @ordered
   */
  protected static final int GRIDSCALE_EDEFAULT = 0;

  /**
   * The cached value of the '{@link #getGridscale() <em>Gridscale</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getGridscale()
   * @generated
   * @ordered
   */
  protected int gridscale = GRIDSCALE_EDEFAULT;

  /**
   * The default value of the '{@link #getLegendstyle() <em>Legendstyle</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getLegendstyle()
   * @generated
   * @ordered
   */
  protected static final LegendStyle LEGENDSTYLE_EDEFAULT = LegendStyle.LEGEND1;

  /**
   * The cached value of the '{@link #getLegendstyle() <em>Legendstyle</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getLegendstyle()
   * @generated
   * @ordered
   */
  protected LegendStyle legendstyle = LEGENDSTYLE_EDEFAULT;

  /**
   * The default value of the '{@link #getPadding() <em>Padding</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getPadding()
   * @generated
   * @ordered
   */
  protected static final int PADDING_EDEFAULT = 0;

  /**
   * The cached value of the '{@link #getPadding() <em>Padding</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getPadding()
   * @generated
   * @ordered
   */
  protected int padding = PADDING_EDEFAULT;

  /**
   * The default value of the '{@link #getPosition() <em>Position</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getPosition()
   * @generated
   * @ordered
   */
  protected static final String POSITION_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getPosition() <em>Position</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getPosition()
   * @generated
   * @ordered
   */
  protected String position = POSITION_EDEFAULT;

  /**
   * The default value of the '{@link #getShowgrid() <em>Showgrid</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getShowgrid()
   * @generated
   * @ordered
   */
  protected static final ShowOptionsOff SHOWGRID_EDEFAULT = ShowOptionsOff.SHOW1;

  /**
   * The cached value of the '{@link #getShowgrid() <em>Showgrid</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getShowgrid()
   * @generated
   * @ordered
   */
  protected ShowOptionsOff showgrid = SHOWGRID_EDEFAULT;

  /**
   * The default value of the '{@link #getShowlegend() <em>Showlegend</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getShowlegend()
   * @generated
   * @ordered
   */
  protected static final ShowOptionsOff SHOWLEGEND_EDEFAULT = ShowOptionsOff.SHOW1;

  /**
   * The cached value of the '{@link #getShowlegend() <em>Showlegend</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getShowlegend()
   * @generated
   * @ordered
   */
  protected ShowOptionsOff showlegend = SHOWLEGEND_EDEFAULT;

  /**
   * The default value of the '{@link #getShowtitle() <em>Showtitle</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getShowtitle()
   * @generated
   * @ordered
   */
  protected static final ShowOptionsOff SHOWTITLE_EDEFAULT = ShowOptionsOff.SHOW1;

  /**
   * The cached value of the '{@link #getShowtitle() <em>Showtitle</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getShowtitle()
   * @generated
   * @ordered
   */
  protected ShowOptionsOff showtitle = SHOWTITLE_EDEFAULT;

  /**
   * The default value of the '{@link #getSize() <em>Size</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getSize()
   * @generated
   * @ordered
   */
  protected static final String SIZE_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getSize() <em>Size</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getSize()
   * @generated
   * @ordered
   */
  protected String size = SIZE_EDEFAULT;

  /**
   * The default value of the '{@link #getTitle() <em>Title</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getTitle()
   * @generated
   * @ordered
   */
  protected static final String TITLE_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getTitle() <em>Title</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getTitle()
   * @generated
   * @ordered
   */
  protected String title = TITLE_EDEFAULT;

  /**
   * The default value of the '{@link #getType() <em>Type</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getType()
   * @generated
   * @ordered
   */
  protected static final BarType TYPE_EDEFAULT = BarType.TYPE1;

  /**
   * The cached value of the '{@link #getType() <em>Type</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getType()
   * @generated
   * @ordered
   */
  protected BarType type = TYPE_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected BarchartImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return IDSLPackage.Literals.BARCHART;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getName()
  {
    return name;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setName(String newName)
  {
    String oldName = name;
    name = newName;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, IDSLPackage.BARCHART__NAME, oldName, name));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Color getColor()
  {
    return color;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetColor(Color newColor, NotificationChain msgs)
  {
    Color oldColor = color;
    color = newColor;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, IDSLPackage.BARCHART__COLOR, oldColor, newColor);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setColor(Color newColor)
  {
    if (newColor != color)
    {
      NotificationChain msgs = null;
      if (color != null)
        msgs = ((InternalEObject)color).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - IDSLPackage.BARCHART__COLOR, null, msgs);
      if (newColor != null)
        msgs = ((InternalEObject)newColor).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - IDSLPackage.BARCHART__COLOR, null, msgs);
      msgs = basicSetColor(newColor, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, IDSLPackage.BARCHART__COLOR, newColor, newColor));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getColors()
  {
    return colors;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setColors(String newColors)
  {
    String oldColors = colors;
    colors = newColors;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, IDSLPackage.BARCHART__COLORS, oldColors, colors));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<String> getBardata()
  {
    if (bardata == null)
    {
      bardata = new EDataTypeEList<String>(String.class, this, IDSLPackage.BARCHART__BARDATA);
    }
    return bardata;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public int getGridscale()
  {
    return gridscale;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setGridscale(int newGridscale)
  {
    int oldGridscale = gridscale;
    gridscale = newGridscale;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, IDSLPackage.BARCHART__GRIDSCALE, oldGridscale, gridscale));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public LegendStyle getLegendstyle()
  {
    return legendstyle;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setLegendstyle(LegendStyle newLegendstyle)
  {
    LegendStyle oldLegendstyle = legendstyle;
    legendstyle = newLegendstyle == null ? LEGENDSTYLE_EDEFAULT : newLegendstyle;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, IDSLPackage.BARCHART__LEGENDSTYLE, oldLegendstyle, legendstyle));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public int getPadding()
  {
    return padding;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setPadding(int newPadding)
  {
    int oldPadding = padding;
    padding = newPadding;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, IDSLPackage.BARCHART__PADDING, oldPadding, padding));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getPosition()
  {
    return position;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setPosition(String newPosition)
  {
    String oldPosition = position;
    position = newPosition;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, IDSLPackage.BARCHART__POSITION, oldPosition, position));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public ShowOptionsOff getShowgrid()
  {
    return showgrid;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setShowgrid(ShowOptionsOff newShowgrid)
  {
    ShowOptionsOff oldShowgrid = showgrid;
    showgrid = newShowgrid == null ? SHOWGRID_EDEFAULT : newShowgrid;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, IDSLPackage.BARCHART__SHOWGRID, oldShowgrid, showgrid));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public ShowOptionsOff getShowlegend()
  {
    return showlegend;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setShowlegend(ShowOptionsOff newShowlegend)
  {
    ShowOptionsOff oldShowlegend = showlegend;
    showlegend = newShowlegend == null ? SHOWLEGEND_EDEFAULT : newShowlegend;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, IDSLPackage.BARCHART__SHOWLEGEND, oldShowlegend, showlegend));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public ShowOptionsOff getShowtitle()
  {
    return showtitle;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setShowtitle(ShowOptionsOff newShowtitle)
  {
    ShowOptionsOff oldShowtitle = showtitle;
    showtitle = newShowtitle == null ? SHOWTITLE_EDEFAULT : newShowtitle;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, IDSLPackage.BARCHART__SHOWTITLE, oldShowtitle, showtitle));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getSize()
  {
    return size;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setSize(String newSize)
  {
    String oldSize = size;
    size = newSize;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, IDSLPackage.BARCHART__SIZE, oldSize, size));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getTitle()
  {
    return title;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setTitle(String newTitle)
  {
    String oldTitle = title;
    title = newTitle;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, IDSLPackage.BARCHART__TITLE, oldTitle, title));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public BarType getType()
  {
    return type;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setType(BarType newType)
  {
    BarType oldType = type;
    type = newType == null ? TYPE_EDEFAULT : newType;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, IDSLPackage.BARCHART__TYPE, oldType, type));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case IDSLPackage.BARCHART__COLOR:
        return basicSetColor(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case IDSLPackage.BARCHART__NAME:
        return getName();
      case IDSLPackage.BARCHART__COLOR:
        return getColor();
      case IDSLPackage.BARCHART__COLORS:
        return getColors();
      case IDSLPackage.BARCHART__BARDATA:
        return getBardata();
      case IDSLPackage.BARCHART__GRIDSCALE:
        return getGridscale();
      case IDSLPackage.BARCHART__LEGENDSTYLE:
        return getLegendstyle();
      case IDSLPackage.BARCHART__PADDING:
        return getPadding();
      case IDSLPackage.BARCHART__POSITION:
        return getPosition();
      case IDSLPackage.BARCHART__SHOWGRID:
        return getShowgrid();
      case IDSLPackage.BARCHART__SHOWLEGEND:
        return getShowlegend();
      case IDSLPackage.BARCHART__SHOWTITLE:
        return getShowtitle();
      case IDSLPackage.BARCHART__SIZE:
        return getSize();
      case IDSLPackage.BARCHART__TITLE:
        return getTitle();
      case IDSLPackage.BARCHART__TYPE:
        return getType();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case IDSLPackage.BARCHART__NAME:
        setName((String)newValue);
        return;
      case IDSLPackage.BARCHART__COLOR:
        setColor((Color)newValue);
        return;
      case IDSLPackage.BARCHART__COLORS:
        setColors((String)newValue);
        return;
      case IDSLPackage.BARCHART__BARDATA:
        getBardata().clear();
        getBardata().addAll((Collection<? extends String>)newValue);
        return;
      case IDSLPackage.BARCHART__GRIDSCALE:
        setGridscale((Integer)newValue);
        return;
      case IDSLPackage.BARCHART__LEGENDSTYLE:
        setLegendstyle((LegendStyle)newValue);
        return;
      case IDSLPackage.BARCHART__PADDING:
        setPadding((Integer)newValue);
        return;
      case IDSLPackage.BARCHART__POSITION:
        setPosition((String)newValue);
        return;
      case IDSLPackage.BARCHART__SHOWGRID:
        setShowgrid((ShowOptionsOff)newValue);
        return;
      case IDSLPackage.BARCHART__SHOWLEGEND:
        setShowlegend((ShowOptionsOff)newValue);
        return;
      case IDSLPackage.BARCHART__SHOWTITLE:
        setShowtitle((ShowOptionsOff)newValue);
        return;
      case IDSLPackage.BARCHART__SIZE:
        setSize((String)newValue);
        return;
      case IDSLPackage.BARCHART__TITLE:
        setTitle((String)newValue);
        return;
      case IDSLPackage.BARCHART__TYPE:
        setType((BarType)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case IDSLPackage.BARCHART__NAME:
        setName(NAME_EDEFAULT);
        return;
      case IDSLPackage.BARCHART__COLOR:
        setColor((Color)null);
        return;
      case IDSLPackage.BARCHART__COLORS:
        setColors(COLORS_EDEFAULT);
        return;
      case IDSLPackage.BARCHART__BARDATA:
        getBardata().clear();
        return;
      case IDSLPackage.BARCHART__GRIDSCALE:
        setGridscale(GRIDSCALE_EDEFAULT);
        return;
      case IDSLPackage.BARCHART__LEGENDSTYLE:
        setLegendstyle(LEGENDSTYLE_EDEFAULT);
        return;
      case IDSLPackage.BARCHART__PADDING:
        setPadding(PADDING_EDEFAULT);
        return;
      case IDSLPackage.BARCHART__POSITION:
        setPosition(POSITION_EDEFAULT);
        return;
      case IDSLPackage.BARCHART__SHOWGRID:
        setShowgrid(SHOWGRID_EDEFAULT);
        return;
      case IDSLPackage.BARCHART__SHOWLEGEND:
        setShowlegend(SHOWLEGEND_EDEFAULT);
        return;
      case IDSLPackage.BARCHART__SHOWTITLE:
        setShowtitle(SHOWTITLE_EDEFAULT);
        return;
      case IDSLPackage.BARCHART__SIZE:
        setSize(SIZE_EDEFAULT);
        return;
      case IDSLPackage.BARCHART__TITLE:
        setTitle(TITLE_EDEFAULT);
        return;
      case IDSLPackage.BARCHART__TYPE:
        setType(TYPE_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case IDSLPackage.BARCHART__NAME:
        return NAME_EDEFAULT == null ? name != null : !NAME_EDEFAULT.equals(name);
      case IDSLPackage.BARCHART__COLOR:
        return color != null;
      case IDSLPackage.BARCHART__COLORS:
        return COLORS_EDEFAULT == null ? colors != null : !COLORS_EDEFAULT.equals(colors);
      case IDSLPackage.BARCHART__BARDATA:
        return bardata != null && !bardata.isEmpty();
      case IDSLPackage.BARCHART__GRIDSCALE:
        return gridscale != GRIDSCALE_EDEFAULT;
      case IDSLPackage.BARCHART__LEGENDSTYLE:
        return legendstyle != LEGENDSTYLE_EDEFAULT;
      case IDSLPackage.BARCHART__PADDING:
        return padding != PADDING_EDEFAULT;
      case IDSLPackage.BARCHART__POSITION:
        return POSITION_EDEFAULT == null ? position != null : !POSITION_EDEFAULT.equals(position);
      case IDSLPackage.BARCHART__SHOWGRID:
        return showgrid != SHOWGRID_EDEFAULT;
      case IDSLPackage.BARCHART__SHOWLEGEND:
        return showlegend != SHOWLEGEND_EDEFAULT;
      case IDSLPackage.BARCHART__SHOWTITLE:
        return showtitle != SHOWTITLE_EDEFAULT;
      case IDSLPackage.BARCHART__SIZE:
        return SIZE_EDEFAULT == null ? size != null : !SIZE_EDEFAULT.equals(size);
      case IDSLPackage.BARCHART__TITLE:
        return TITLE_EDEFAULT == null ? title != null : !TITLE_EDEFAULT.equals(title);
      case IDSLPackage.BARCHART__TYPE:
        return type != TYPE_EDEFAULT;
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (name: ");
    result.append(name);
    result.append(", colors: ");
    result.append(colors);
    result.append(", bardata: ");
    result.append(bardata);
    result.append(", gridscale: ");
    result.append(gridscale);
    result.append(", legendstyle: ");
    result.append(legendstyle);
    result.append(", padding: ");
    result.append(padding);
    result.append(", position: ");
    result.append(position);
    result.append(", showgrid: ");
    result.append(showgrid);
    result.append(", showlegend: ");
    result.append(showlegend);
    result.append(", showtitle: ");
    result.append(showtitle);
    result.append(", size: ");
    result.append(size);
    result.append(", title: ");
    result.append(title);
    result.append(", type: ");
    result.append(type);
    result.append(')');
    return result.toString();
  }

} //BarchartImpl
