/**
 * generated by Xtext 2.19.0
 */
package org.xtext.example.mydsl.iDSL.impl;

import java.util.Collection;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.eclipse.emf.ecore.util.EDataTypeEList;

import org.xtext.example.mydsl.iDSL.Color;
import org.xtext.example.mydsl.iDSL.IDSLPackage;
import org.xtext.example.mydsl.iDSL.LegendStyle;
import org.xtext.example.mydsl.iDSL.PieType;
import org.xtext.example.mydsl.iDSL.Piechart;
import org.xtext.example.mydsl.iDSL.ShowOptionsOff;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Piechart</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.iDSL.impl.PiechartImpl#getName <em>Name</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.iDSL.impl.PiechartImpl#getColor <em>Color</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.iDSL.impl.PiechartImpl#getColors <em>Colors</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.iDSL.impl.PiechartImpl#getPiedata <em>Piedata</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.iDSL.impl.PiechartImpl#getLegendstyle <em>Legendstyle</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.iDSL.impl.PiechartImpl#getPadding <em>Padding</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.iDSL.impl.PiechartImpl#getPosition <em>Position</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.iDSL.impl.PiechartImpl#getShowlegend <em>Showlegend</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.iDSL.impl.PiechartImpl#getShowtitle <em>Showtitle</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.iDSL.impl.PiechartImpl#getShowpercentage <em>Showpercentage</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.iDSL.impl.PiechartImpl#getSize <em>Size</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.iDSL.impl.PiechartImpl#getTitle <em>Title</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.iDSL.impl.PiechartImpl#getType <em>Type</em>}</li>
 * </ul>
 *
 * @generated
 */
public class PiechartImpl extends MinimalEObjectImpl.Container implements Piechart
{
  /**
   * The default value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected static final String NAME_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected String name = NAME_EDEFAULT;

  /**
   * The cached value of the '{@link #getColor() <em>Color</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getColor()
   * @generated
   * @ordered
   */
  protected Color color;

  /**
   * The default value of the '{@link #getColors() <em>Colors</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getColors()
   * @generated
   * @ordered
   */
  protected static final String COLORS_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getColors() <em>Colors</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getColors()
   * @generated
   * @ordered
   */
  protected String colors = COLORS_EDEFAULT;

  /**
   * The cached value of the '{@link #getPiedata() <em>Piedata</em>}' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getPiedata()
   * @generated
   * @ordered
   */
  protected EList<String> piedata;

  /**
   * The default value of the '{@link #getLegendstyle() <em>Legendstyle</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getLegendstyle()
   * @generated
   * @ordered
   */
  protected static final LegendStyle LEGENDSTYLE_EDEFAULT = LegendStyle.LEGEND1;

  /**
   * The cached value of the '{@link #getLegendstyle() <em>Legendstyle</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getLegendstyle()
   * @generated
   * @ordered
   */
  protected LegendStyle legendstyle = LEGENDSTYLE_EDEFAULT;

  /**
   * The default value of the '{@link #getPadding() <em>Padding</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getPadding()
   * @generated
   * @ordered
   */
  protected static final int PADDING_EDEFAULT = 0;

  /**
   * The cached value of the '{@link #getPadding() <em>Padding</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getPadding()
   * @generated
   * @ordered
   */
  protected int padding = PADDING_EDEFAULT;

  /**
   * The default value of the '{@link #getPosition() <em>Position</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getPosition()
   * @generated
   * @ordered
   */
  protected static final String POSITION_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getPosition() <em>Position</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getPosition()
   * @generated
   * @ordered
   */
  protected String position = POSITION_EDEFAULT;

  /**
   * The default value of the '{@link #getShowlegend() <em>Showlegend</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getShowlegend()
   * @generated
   * @ordered
   */
  protected static final ShowOptionsOff SHOWLEGEND_EDEFAULT = ShowOptionsOff.SHOW1;

  /**
   * The cached value of the '{@link #getShowlegend() <em>Showlegend</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getShowlegend()
   * @generated
   * @ordered
   */
  protected ShowOptionsOff showlegend = SHOWLEGEND_EDEFAULT;

  /**
   * The default value of the '{@link #getShowtitle() <em>Showtitle</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getShowtitle()
   * @generated
   * @ordered
   */
  protected static final ShowOptionsOff SHOWTITLE_EDEFAULT = ShowOptionsOff.SHOW1;

  /**
   * The cached value of the '{@link #getShowtitle() <em>Showtitle</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getShowtitle()
   * @generated
   * @ordered
   */
  protected ShowOptionsOff showtitle = SHOWTITLE_EDEFAULT;

  /**
   * The default value of the '{@link #getShowpercentage() <em>Showpercentage</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getShowpercentage()
   * @generated
   * @ordered
   */
  protected static final ShowOptionsOff SHOWPERCENTAGE_EDEFAULT = ShowOptionsOff.SHOW1;

  /**
   * The cached value of the '{@link #getShowpercentage() <em>Showpercentage</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getShowpercentage()
   * @generated
   * @ordered
   */
  protected ShowOptionsOff showpercentage = SHOWPERCENTAGE_EDEFAULT;

  /**
   * The default value of the '{@link #getSize() <em>Size</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getSize()
   * @generated
   * @ordered
   */
  protected static final int SIZE_EDEFAULT = 0;

  /**
   * The cached value of the '{@link #getSize() <em>Size</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getSize()
   * @generated
   * @ordered
   */
  protected int size = SIZE_EDEFAULT;

  /**
   * The default value of the '{@link #getTitle() <em>Title</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getTitle()
   * @generated
   * @ordered
   */
  protected static final String TITLE_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getTitle() <em>Title</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getTitle()
   * @generated
   * @ordered
   */
  protected String title = TITLE_EDEFAULT;

  /**
   * The default value of the '{@link #getType() <em>Type</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getType()
   * @generated
   * @ordered
   */
  protected static final PieType TYPE_EDEFAULT = PieType.TYPE1;

  /**
   * The cached value of the '{@link #getType() <em>Type</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getType()
   * @generated
   * @ordered
   */
  protected PieType type = TYPE_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected PiechartImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return IDSLPackage.Literals.PIECHART;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getName()
  {
    return name;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setName(String newName)
  {
    String oldName = name;
    name = newName;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, IDSLPackage.PIECHART__NAME, oldName, name));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Color getColor()
  {
    return color;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetColor(Color newColor, NotificationChain msgs)
  {
    Color oldColor = color;
    color = newColor;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, IDSLPackage.PIECHART__COLOR, oldColor, newColor);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setColor(Color newColor)
  {
    if (newColor != color)
    {
      NotificationChain msgs = null;
      if (color != null)
        msgs = ((InternalEObject)color).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - IDSLPackage.PIECHART__COLOR, null, msgs);
      if (newColor != null)
        msgs = ((InternalEObject)newColor).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - IDSLPackage.PIECHART__COLOR, null, msgs);
      msgs = basicSetColor(newColor, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, IDSLPackage.PIECHART__COLOR, newColor, newColor));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getColors()
  {
    return colors;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setColors(String newColors)
  {
    String oldColors = colors;
    colors = newColors;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, IDSLPackage.PIECHART__COLORS, oldColors, colors));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<String> getPiedata()
  {
    if (piedata == null)
    {
      piedata = new EDataTypeEList<String>(String.class, this, IDSLPackage.PIECHART__PIEDATA);
    }
    return piedata;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public LegendStyle getLegendstyle()
  {
    return legendstyle;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setLegendstyle(LegendStyle newLegendstyle)
  {
    LegendStyle oldLegendstyle = legendstyle;
    legendstyle = newLegendstyle == null ? LEGENDSTYLE_EDEFAULT : newLegendstyle;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, IDSLPackage.PIECHART__LEGENDSTYLE, oldLegendstyle, legendstyle));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public int getPadding()
  {
    return padding;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setPadding(int newPadding)
  {
    int oldPadding = padding;
    padding = newPadding;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, IDSLPackage.PIECHART__PADDING, oldPadding, padding));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getPosition()
  {
    return position;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setPosition(String newPosition)
  {
    String oldPosition = position;
    position = newPosition;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, IDSLPackage.PIECHART__POSITION, oldPosition, position));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public ShowOptionsOff getShowlegend()
  {
    return showlegend;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setShowlegend(ShowOptionsOff newShowlegend)
  {
    ShowOptionsOff oldShowlegend = showlegend;
    showlegend = newShowlegend == null ? SHOWLEGEND_EDEFAULT : newShowlegend;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, IDSLPackage.PIECHART__SHOWLEGEND, oldShowlegend, showlegend));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public ShowOptionsOff getShowtitle()
  {
    return showtitle;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setShowtitle(ShowOptionsOff newShowtitle)
  {
    ShowOptionsOff oldShowtitle = showtitle;
    showtitle = newShowtitle == null ? SHOWTITLE_EDEFAULT : newShowtitle;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, IDSLPackage.PIECHART__SHOWTITLE, oldShowtitle, showtitle));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public ShowOptionsOff getShowpercentage()
  {
    return showpercentage;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setShowpercentage(ShowOptionsOff newShowpercentage)
  {
    ShowOptionsOff oldShowpercentage = showpercentage;
    showpercentage = newShowpercentage == null ? SHOWPERCENTAGE_EDEFAULT : newShowpercentage;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, IDSLPackage.PIECHART__SHOWPERCENTAGE, oldShowpercentage, showpercentage));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public int getSize()
  {
    return size;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setSize(int newSize)
  {
    int oldSize = size;
    size = newSize;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, IDSLPackage.PIECHART__SIZE, oldSize, size));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getTitle()
  {
    return title;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setTitle(String newTitle)
  {
    String oldTitle = title;
    title = newTitle;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, IDSLPackage.PIECHART__TITLE, oldTitle, title));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public PieType getType()
  {
    return type;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setType(PieType newType)
  {
    PieType oldType = type;
    type = newType == null ? TYPE_EDEFAULT : newType;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, IDSLPackage.PIECHART__TYPE, oldType, type));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case IDSLPackage.PIECHART__COLOR:
        return basicSetColor(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case IDSLPackage.PIECHART__NAME:
        return getName();
      case IDSLPackage.PIECHART__COLOR:
        return getColor();
      case IDSLPackage.PIECHART__COLORS:
        return getColors();
      case IDSLPackage.PIECHART__PIEDATA:
        return getPiedata();
      case IDSLPackage.PIECHART__LEGENDSTYLE:
        return getLegendstyle();
      case IDSLPackage.PIECHART__PADDING:
        return getPadding();
      case IDSLPackage.PIECHART__POSITION:
        return getPosition();
      case IDSLPackage.PIECHART__SHOWLEGEND:
        return getShowlegend();
      case IDSLPackage.PIECHART__SHOWTITLE:
        return getShowtitle();
      case IDSLPackage.PIECHART__SHOWPERCENTAGE:
        return getShowpercentage();
      case IDSLPackage.PIECHART__SIZE:
        return getSize();
      case IDSLPackage.PIECHART__TITLE:
        return getTitle();
      case IDSLPackage.PIECHART__TYPE:
        return getType();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case IDSLPackage.PIECHART__NAME:
        setName((String)newValue);
        return;
      case IDSLPackage.PIECHART__COLOR:
        setColor((Color)newValue);
        return;
      case IDSLPackage.PIECHART__COLORS:
        setColors((String)newValue);
        return;
      case IDSLPackage.PIECHART__PIEDATA:
        getPiedata().clear();
        getPiedata().addAll((Collection<? extends String>)newValue);
        return;
      case IDSLPackage.PIECHART__LEGENDSTYLE:
        setLegendstyle((LegendStyle)newValue);
        return;
      case IDSLPackage.PIECHART__PADDING:
        setPadding((Integer)newValue);
        return;
      case IDSLPackage.PIECHART__POSITION:
        setPosition((String)newValue);
        return;
      case IDSLPackage.PIECHART__SHOWLEGEND:
        setShowlegend((ShowOptionsOff)newValue);
        return;
      case IDSLPackage.PIECHART__SHOWTITLE:
        setShowtitle((ShowOptionsOff)newValue);
        return;
      case IDSLPackage.PIECHART__SHOWPERCENTAGE:
        setShowpercentage((ShowOptionsOff)newValue);
        return;
      case IDSLPackage.PIECHART__SIZE:
        setSize((Integer)newValue);
        return;
      case IDSLPackage.PIECHART__TITLE:
        setTitle((String)newValue);
        return;
      case IDSLPackage.PIECHART__TYPE:
        setType((PieType)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case IDSLPackage.PIECHART__NAME:
        setName(NAME_EDEFAULT);
        return;
      case IDSLPackage.PIECHART__COLOR:
        setColor((Color)null);
        return;
      case IDSLPackage.PIECHART__COLORS:
        setColors(COLORS_EDEFAULT);
        return;
      case IDSLPackage.PIECHART__PIEDATA:
        getPiedata().clear();
        return;
      case IDSLPackage.PIECHART__LEGENDSTYLE:
        setLegendstyle(LEGENDSTYLE_EDEFAULT);
        return;
      case IDSLPackage.PIECHART__PADDING:
        setPadding(PADDING_EDEFAULT);
        return;
      case IDSLPackage.PIECHART__POSITION:
        setPosition(POSITION_EDEFAULT);
        return;
      case IDSLPackage.PIECHART__SHOWLEGEND:
        setShowlegend(SHOWLEGEND_EDEFAULT);
        return;
      case IDSLPackage.PIECHART__SHOWTITLE:
        setShowtitle(SHOWTITLE_EDEFAULT);
        return;
      case IDSLPackage.PIECHART__SHOWPERCENTAGE:
        setShowpercentage(SHOWPERCENTAGE_EDEFAULT);
        return;
      case IDSLPackage.PIECHART__SIZE:
        setSize(SIZE_EDEFAULT);
        return;
      case IDSLPackage.PIECHART__TITLE:
        setTitle(TITLE_EDEFAULT);
        return;
      case IDSLPackage.PIECHART__TYPE:
        setType(TYPE_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case IDSLPackage.PIECHART__NAME:
        return NAME_EDEFAULT == null ? name != null : !NAME_EDEFAULT.equals(name);
      case IDSLPackage.PIECHART__COLOR:
        return color != null;
      case IDSLPackage.PIECHART__COLORS:
        return COLORS_EDEFAULT == null ? colors != null : !COLORS_EDEFAULT.equals(colors);
      case IDSLPackage.PIECHART__PIEDATA:
        return piedata != null && !piedata.isEmpty();
      case IDSLPackage.PIECHART__LEGENDSTYLE:
        return legendstyle != LEGENDSTYLE_EDEFAULT;
      case IDSLPackage.PIECHART__PADDING:
        return padding != PADDING_EDEFAULT;
      case IDSLPackage.PIECHART__POSITION:
        return POSITION_EDEFAULT == null ? position != null : !POSITION_EDEFAULT.equals(position);
      case IDSLPackage.PIECHART__SHOWLEGEND:
        return showlegend != SHOWLEGEND_EDEFAULT;
      case IDSLPackage.PIECHART__SHOWTITLE:
        return showtitle != SHOWTITLE_EDEFAULT;
      case IDSLPackage.PIECHART__SHOWPERCENTAGE:
        return showpercentage != SHOWPERCENTAGE_EDEFAULT;
      case IDSLPackage.PIECHART__SIZE:
        return size != SIZE_EDEFAULT;
      case IDSLPackage.PIECHART__TITLE:
        return TITLE_EDEFAULT == null ? title != null : !TITLE_EDEFAULT.equals(title);
      case IDSLPackage.PIECHART__TYPE:
        return type != TYPE_EDEFAULT;
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (name: ");
    result.append(name);
    result.append(", colors: ");
    result.append(colors);
    result.append(", piedata: ");
    result.append(piedata);
    result.append(", legendstyle: ");
    result.append(legendstyle);
    result.append(", padding: ");
    result.append(padding);
    result.append(", position: ");
    result.append(position);
    result.append(", showlegend: ");
    result.append(showlegend);
    result.append(", showtitle: ");
    result.append(showtitle);
    result.append(", showpercentage: ");
    result.append(showpercentage);
    result.append(", size: ");
    result.append(size);
    result.append(", title: ");
    result.append(title);
    result.append(", type: ");
    result.append(type);
    result.append(')');
    return result.toString();
  }

} //PiechartImpl
