/*
 * generated by Xtext 2.19.0
 */
package org.xtext.example.mydsl.ui;

import com.google.inject.Injector;
import org.eclipse.core.runtime.Platform;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.xtext.example.InfographicDSL.ui.internal.InfographicDSLActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class IDSLExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return Platform.getBundle(InfographicDSLActivator.PLUGIN_ID);
	}
	
	@Override
	protected Injector getInjector() {
		InfographicDSLActivator activator = InfographicDSLActivator.getInstance();
		return activator != null ? activator.getInjector(InfographicDSLActivator.ORG_XTEXT_EXAMPLE_MYDSL_IDSL) : null;
	}

}
