/**
 * generated by Xtext 2.19.0
 */
package org.xtext.example.mydsl.iDSL;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Barchart</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.iDSL.Barchart#getName <em>Name</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.iDSL.Barchart#getColor <em>Color</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.iDSL.Barchart#getColors <em>Colors</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.iDSL.Barchart#getBardata <em>Bardata</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.iDSL.Barchart#getGridscale <em>Gridscale</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.iDSL.Barchart#getLegendstyle <em>Legendstyle</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.iDSL.Barchart#getPadding <em>Padding</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.iDSL.Barchart#getPosition <em>Position</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.iDSL.Barchart#getShowgrid <em>Showgrid</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.iDSL.Barchart#getShowlegend <em>Showlegend</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.iDSL.Barchart#getShowtitle <em>Showtitle</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.iDSL.Barchart#getSize <em>Size</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.iDSL.Barchart#getTitle <em>Title</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.iDSL.Barchart#getType <em>Type</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.iDSL.IDSLPackage#getBarchart()
 * @model
 * @generated
 */
public interface Barchart extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see org.xtext.example.mydsl.iDSL.IDSLPackage#getBarchart_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.iDSL.Barchart#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Color</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Color</em>' containment reference.
   * @see #setColor(Color)
   * @see org.xtext.example.mydsl.iDSL.IDSLPackage#getBarchart_Color()
   * @model containment="true"
   * @generated
   */
  Color getColor();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.iDSL.Barchart#getColor <em>Color</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Color</em>' containment reference.
   * @see #getColor()
   * @generated
   */
  void setColor(Color value);

  /**
   * Returns the value of the '<em><b>Colors</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Colors</em>' attribute.
   * @see #setColors(String)
   * @see org.xtext.example.mydsl.iDSL.IDSLPackage#getBarchart_Colors()
   * @model
   * @generated
   */
  String getColors();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.iDSL.Barchart#getColors <em>Colors</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Colors</em>' attribute.
   * @see #getColors()
   * @generated
   */
  void setColors(String value);

  /**
   * Returns the value of the '<em><b>Bardata</b></em>' attribute list.
   * The list contents are of type {@link java.lang.String}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Bardata</em>' attribute list.
   * @see org.xtext.example.mydsl.iDSL.IDSLPackage#getBarchart_Bardata()
   * @model unique="false"
   * @generated
   */
  EList<String> getBardata();

  /**
   * Returns the value of the '<em><b>Gridscale</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Gridscale</em>' attribute.
   * @see #setGridscale(int)
   * @see org.xtext.example.mydsl.iDSL.IDSLPackage#getBarchart_Gridscale()
   * @model
   * @generated
   */
  int getGridscale();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.iDSL.Barchart#getGridscale <em>Gridscale</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Gridscale</em>' attribute.
   * @see #getGridscale()
   * @generated
   */
  void setGridscale(int value);

  /**
   * Returns the value of the '<em><b>Legendstyle</b></em>' attribute.
   * The literals are from the enumeration {@link org.xtext.example.mydsl.iDSL.LegendStyle}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Legendstyle</em>' attribute.
   * @see org.xtext.example.mydsl.iDSL.LegendStyle
   * @see #setLegendstyle(LegendStyle)
   * @see org.xtext.example.mydsl.iDSL.IDSLPackage#getBarchart_Legendstyle()
   * @model
   * @generated
   */
  LegendStyle getLegendstyle();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.iDSL.Barchart#getLegendstyle <em>Legendstyle</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Legendstyle</em>' attribute.
   * @see org.xtext.example.mydsl.iDSL.LegendStyle
   * @see #getLegendstyle()
   * @generated
   */
  void setLegendstyle(LegendStyle value);

  /**
   * Returns the value of the '<em><b>Padding</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Padding</em>' attribute.
   * @see #setPadding(int)
   * @see org.xtext.example.mydsl.iDSL.IDSLPackage#getBarchart_Padding()
   * @model
   * @generated
   */
  int getPadding();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.iDSL.Barchart#getPadding <em>Padding</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Padding</em>' attribute.
   * @see #getPadding()
   * @generated
   */
  void setPadding(int value);

  /**
   * Returns the value of the '<em><b>Position</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Position</em>' attribute.
   * @see #setPosition(String)
   * @see org.xtext.example.mydsl.iDSL.IDSLPackage#getBarchart_Position()
   * @model
   * @generated
   */
  String getPosition();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.iDSL.Barchart#getPosition <em>Position</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Position</em>' attribute.
   * @see #getPosition()
   * @generated
   */
  void setPosition(String value);

  /**
   * Returns the value of the '<em><b>Showgrid</b></em>' attribute.
   * The literals are from the enumeration {@link org.xtext.example.mydsl.iDSL.ShowOptionsOff}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Showgrid</em>' attribute.
   * @see org.xtext.example.mydsl.iDSL.ShowOptionsOff
   * @see #setShowgrid(ShowOptionsOff)
   * @see org.xtext.example.mydsl.iDSL.IDSLPackage#getBarchart_Showgrid()
   * @model
   * @generated
   */
  ShowOptionsOff getShowgrid();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.iDSL.Barchart#getShowgrid <em>Showgrid</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Showgrid</em>' attribute.
   * @see org.xtext.example.mydsl.iDSL.ShowOptionsOff
   * @see #getShowgrid()
   * @generated
   */
  void setShowgrid(ShowOptionsOff value);

  /**
   * Returns the value of the '<em><b>Showlegend</b></em>' attribute.
   * The literals are from the enumeration {@link org.xtext.example.mydsl.iDSL.ShowOptionsOff}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Showlegend</em>' attribute.
   * @see org.xtext.example.mydsl.iDSL.ShowOptionsOff
   * @see #setShowlegend(ShowOptionsOff)
   * @see org.xtext.example.mydsl.iDSL.IDSLPackage#getBarchart_Showlegend()
   * @model
   * @generated
   */
  ShowOptionsOff getShowlegend();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.iDSL.Barchart#getShowlegend <em>Showlegend</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Showlegend</em>' attribute.
   * @see org.xtext.example.mydsl.iDSL.ShowOptionsOff
   * @see #getShowlegend()
   * @generated
   */
  void setShowlegend(ShowOptionsOff value);

  /**
   * Returns the value of the '<em><b>Showtitle</b></em>' attribute.
   * The literals are from the enumeration {@link org.xtext.example.mydsl.iDSL.ShowOptionsOff}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Showtitle</em>' attribute.
   * @see org.xtext.example.mydsl.iDSL.ShowOptionsOff
   * @see #setShowtitle(ShowOptionsOff)
   * @see org.xtext.example.mydsl.iDSL.IDSLPackage#getBarchart_Showtitle()
   * @model
   * @generated
   */
  ShowOptionsOff getShowtitle();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.iDSL.Barchart#getShowtitle <em>Showtitle</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Showtitle</em>' attribute.
   * @see org.xtext.example.mydsl.iDSL.ShowOptionsOff
   * @see #getShowtitle()
   * @generated
   */
  void setShowtitle(ShowOptionsOff value);

  /**
   * Returns the value of the '<em><b>Size</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Size</em>' attribute.
   * @see #setSize(String)
   * @see org.xtext.example.mydsl.iDSL.IDSLPackage#getBarchart_Size()
   * @model
   * @generated
   */
  String getSize();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.iDSL.Barchart#getSize <em>Size</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Size</em>' attribute.
   * @see #getSize()
   * @generated
   */
  void setSize(String value);

  /**
   * Returns the value of the '<em><b>Title</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Title</em>' attribute.
   * @see #setTitle(String)
   * @see org.xtext.example.mydsl.iDSL.IDSLPackage#getBarchart_Title()
   * @model
   * @generated
   */
  String getTitle();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.iDSL.Barchart#getTitle <em>Title</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Title</em>' attribute.
   * @see #getTitle()
   * @generated
   */
  void setTitle(String value);

  /**
   * Returns the value of the '<em><b>Type</b></em>' attribute.
   * The literals are from the enumeration {@link org.xtext.example.mydsl.iDSL.BarType}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Type</em>' attribute.
   * @see org.xtext.example.mydsl.iDSL.BarType
   * @see #setType(BarType)
   * @see org.xtext.example.mydsl.iDSL.IDSLPackage#getBarchart_Type()
   * @model
   * @generated
   */
  BarType getType();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.iDSL.Barchart#getType <em>Type</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Type</em>' attribute.
   * @see org.xtext.example.mydsl.iDSL.BarType
   * @see #getType()
   * @generated
   */
  void setType(BarType value);

} // Barchart
