/**
 * generated by Xtext 2.19.0
 */
package org.xtext.example.mydsl.iDSL;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Box</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.iDSL.Box#getName <em>Name</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.iDSL.Box#getBgcolor <em>Bgcolor</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.iDSL.Box#getBgpattern <em>Bgpattern</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.iDSL.Box#getBgimage <em>Bgimage</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.iDSL.Box#getSize <em>Size</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.iDSL.Box#getPosition <em>Position</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.iDSL.IDSLPackage#getBox()
 * @model
 * @generated
 */
public interface Box extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see org.xtext.example.mydsl.iDSL.IDSLPackage#getBox_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.iDSL.Box#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Bgcolor</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Bgcolor</em>' containment reference.
   * @see #setBgcolor(Color)
   * @see org.xtext.example.mydsl.iDSL.IDSLPackage#getBox_Bgcolor()
   * @model containment="true"
   * @generated
   */
  Color getBgcolor();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.iDSL.Box#getBgcolor <em>Bgcolor</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Bgcolor</em>' containment reference.
   * @see #getBgcolor()
   * @generated
   */
  void setBgcolor(Color value);

  /**
   * Returns the value of the '<em><b>Bgpattern</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Bgpattern</em>' attribute.
   * @see #setBgpattern(String)
   * @see org.xtext.example.mydsl.iDSL.IDSLPackage#getBox_Bgpattern()
   * @model
   * @generated
   */
  String getBgpattern();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.iDSL.Box#getBgpattern <em>Bgpattern</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Bgpattern</em>' attribute.
   * @see #getBgpattern()
   * @generated
   */
  void setBgpattern(String value);

  /**
   * Returns the value of the '<em><b>Bgimage</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Bgimage</em>' attribute.
   * @see #setBgimage(String)
   * @see org.xtext.example.mydsl.iDSL.IDSLPackage#getBox_Bgimage()
   * @model
   * @generated
   */
  String getBgimage();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.iDSL.Box#getBgimage <em>Bgimage</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Bgimage</em>' attribute.
   * @see #getBgimage()
   * @generated
   */
  void setBgimage(String value);

  /**
   * Returns the value of the '<em><b>Size</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Size</em>' attribute.
   * @see #setSize(String)
   * @see org.xtext.example.mydsl.iDSL.IDSLPackage#getBox_Size()
   * @model
   * @generated
   */
  String getSize();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.iDSL.Box#getSize <em>Size</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Size</em>' attribute.
   * @see #getSize()
   * @generated
   */
  void setSize(String value);

  /**
   * Returns the value of the '<em><b>Position</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Position</em>' attribute.
   * @see #setPosition(String)
   * @see org.xtext.example.mydsl.iDSL.IDSLPackage#getBox_Position()
   * @model
   * @generated
   */
  String getPosition();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.iDSL.Box#getPosition <em>Position</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Position</em>' attribute.
   * @see #getPosition()
   * @generated
   */
  void setPosition(String value);

} // Box
