/**
 * generated by Xtext 2.19.0
 */
package org.xtext.example.mydsl.iDSL;

import java.util.Arrays;
import java.util.Collections;
import java.util.List;

import org.eclipse.emf.common.util.Enumerator;

/**
 * <!-- begin-user-doc -->
 * A representation of the literals of the enumeration '<em><b>Font Weight</b></em>',
 * and utility methods for working with them.
 * <!-- end-user-doc -->
 * @see org.xtext.example.mydsl.iDSL.IDSLPackage#getFont_Weight()
 * @model
 * @generated
 */
public enum Font_Weight implements Enumerator
{
  /**
   * The '<em><b>B1</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #B1_VALUE
   * @generated
   * @ordered
   */
  B1(0, "b1", "bold "),

  /**
   * The '<em><b>B2</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #B2_VALUE
   * @generated
   * @ordered
   */
  B2(1, "b2", "100 "),

  /**
   * The '<em><b>B3</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #B3_VALUE
   * @generated
   * @ordered
   */
  B3(2, "b3", "200 "),

  /**
   * The '<em><b>B4</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #B4_VALUE
   * @generated
   * @ordered
   */
  B4(3, "b4", "300 "),

  /**
   * The '<em><b>B5</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #B5_VALUE
   * @generated
   * @ordered
   */
  B5(4, "b5", "400 "),

  /**
   * The '<em><b>B6</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #B6_VALUE
   * @generated
   * @ordered
   */
  B6(5, "b6", "500 "),

  /**
   * The '<em><b>B7</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #B7_VALUE
   * @generated
   * @ordered
   */
  B7(6, "b7", "600 "),

  /**
   * The '<em><b>B8</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #B8_VALUE
   * @generated
   * @ordered
   */
  B8(7, "b8", "700 "),

  /**
   * The '<em><b>B9</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #B9_VALUE
   * @generated
   * @ordered
   */
  B9(8, "b9", "800 "),

  /**
   * The '<em><b>B10</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #B10_VALUE
   * @generated
   * @ordered
   */
  B10(9, "b10", "900 ");

  /**
   * The '<em><b>B1</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #B1
   * @model name="b1" literal="bold "
   * @generated
   * @ordered
   */
  public static final int B1_VALUE = 0;

  /**
   * The '<em><b>B2</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #B2
   * @model name="b2" literal="100 "
   * @generated
   * @ordered
   */
  public static final int B2_VALUE = 1;

  /**
   * The '<em><b>B3</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #B3
   * @model name="b3" literal="200 "
   * @generated
   * @ordered
   */
  public static final int B3_VALUE = 2;

  /**
   * The '<em><b>B4</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #B4
   * @model name="b4" literal="300 "
   * @generated
   * @ordered
   */
  public static final int B4_VALUE = 3;

  /**
   * The '<em><b>B5</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #B5
   * @model name="b5" literal="400 "
   * @generated
   * @ordered
   */
  public static final int B5_VALUE = 4;

  /**
   * The '<em><b>B6</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #B6
   * @model name="b6" literal="500 "
   * @generated
   * @ordered
   */
  public static final int B6_VALUE = 5;

  /**
   * The '<em><b>B7</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #B7
   * @model name="b7" literal="600 "
   * @generated
   * @ordered
   */
  public static final int B7_VALUE = 6;

  /**
   * The '<em><b>B8</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #B8
   * @model name="b8" literal="700 "
   * @generated
   * @ordered
   */
  public static final int B8_VALUE = 7;

  /**
   * The '<em><b>B9</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #B9
   * @model name="b9" literal="800 "
   * @generated
   * @ordered
   */
  public static final int B9_VALUE = 8;

  /**
   * The '<em><b>B10</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #B10
   * @model name="b10" literal="900 "
   * @generated
   * @ordered
   */
  public static final int B10_VALUE = 9;

  /**
   * An array of all the '<em><b>Font Weight</b></em>' enumerators.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private static final Font_Weight[] VALUES_ARRAY =
    new Font_Weight[]
    {
      B1,
      B2,
      B3,
      B4,
      B5,
      B6,
      B7,
      B8,
      B9,
      B10,
    };

  /**
   * A public read-only list of all the '<em><b>Font Weight</b></em>' enumerators.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public static final List<Font_Weight> VALUES = Collections.unmodifiableList(Arrays.asList(VALUES_ARRAY));

  /**
   * Returns the '<em><b>Font Weight</b></em>' literal with the specified literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param literal the literal.
   * @return the matching enumerator or <code>null</code>.
   * @generated
   */
  public static Font_Weight get(String literal)
  {
    for (int i = 0; i < VALUES_ARRAY.length; ++i)
    {
      Font_Weight result = VALUES_ARRAY[i];
      if (result.toString().equals(literal))
      {
        return result;
      }
    }
    return null;
  }

  /**
   * Returns the '<em><b>Font Weight</b></em>' literal with the specified name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param name the name.
   * @return the matching enumerator or <code>null</code>.
   * @generated
   */
  public static Font_Weight getByName(String name)
  {
    for (int i = 0; i < VALUES_ARRAY.length; ++i)
    {
      Font_Weight result = VALUES_ARRAY[i];
      if (result.getName().equals(name))
      {
        return result;
      }
    }
    return null;
  }

  /**
   * Returns the '<em><b>Font Weight</b></em>' literal with the specified integer value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the integer value.
   * @return the matching enumerator or <code>null</code>.
   * @generated
   */
  public static Font_Weight get(int value)
  {
    switch (value)
    {
      case B1_VALUE: return B1;
      case B2_VALUE: return B2;
      case B3_VALUE: return B3;
      case B4_VALUE: return B4;
      case B5_VALUE: return B5;
      case B6_VALUE: return B6;
      case B7_VALUE: return B7;
      case B8_VALUE: return B8;
      case B9_VALUE: return B9;
      case B10_VALUE: return B10;
    }
    return null;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private final int value;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private final String name;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private final String literal;

  /**
   * Only this class can construct instances.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private Font_Weight(int value, String name, String literal)
  {
    this.value = value;
    this.name = name;
    this.literal = literal;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public int getValue()
  {
    return value;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getName()
  {
    return name;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getLiteral()
  {
    return literal;
  }

  /**
   * Returns the literal value of the enumerator, which is its string representation.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    return literal;
  }
  
} //Font_Weight
