/**
 * generated by Xtext 2.19.0
 */
package org.xtext.example.mydsl.iDSL;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>FONT</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.iDSL.FONT#getWeight <em>Weight</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.iDSL.FONT#getFamily <em>Family</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.iDSL.IDSLPackage#getFONT()
 * @model
 * @generated
 */
public interface FONT extends EObject
{
  /**
   * Returns the value of the '<em><b>Weight</b></em>' attribute.
   * The literals are from the enumeration {@link org.xtext.example.mydsl.iDSL.Font_Weight}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Weight</em>' attribute.
   * @see org.xtext.example.mydsl.iDSL.Font_Weight
   * @see #setWeight(Font_Weight)
   * @see org.xtext.example.mydsl.iDSL.IDSLPackage#getFONT_Weight()
   * @model
   * @generated
   */
  Font_Weight getWeight();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.iDSL.FONT#getWeight <em>Weight</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Weight</em>' attribute.
   * @see org.xtext.example.mydsl.iDSL.Font_Weight
   * @see #getWeight()
   * @generated
   */
  void setWeight(Font_Weight value);

  /**
   * Returns the value of the '<em><b>Family</b></em>' attribute.
   * The literals are from the enumeration {@link org.xtext.example.mydsl.iDSL.Font_Family}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Family</em>' attribute.
   * @see org.xtext.example.mydsl.iDSL.Font_Family
   * @see #setFamily(Font_Family)
   * @see org.xtext.example.mydsl.iDSL.IDSLPackage#getFONT_Family()
   * @model
   * @generated
   */
  Font_Family getFamily();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.iDSL.FONT#getFamily <em>Family</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Family</em>' attribute.
   * @see org.xtext.example.mydsl.iDSL.Font_Family
   * @see #getFamily()
   * @generated
   */
  void setFamily(Font_Family value);

} // FONT
