/**
 * generated by Xtext 2.19.0
 */
package org.xtext.example.mydsl.iDSL;

import java.util.Arrays;
import java.util.Collections;
import java.util.List;

import org.eclipse.emf.common.util.Enumerator;

/**
 * <!-- begin-user-doc -->
 * A representation of the literals of the enumeration '<em><b>Font Family</b></em>',
 * and utility methods for working with them.
 * <!-- end-user-doc -->
 * @see org.xtext.example.mydsl.iDSL.IDSLPackage#getFont_Family()
 * @model
 * @generated
 */
public enum Font_Family implements Enumerator
{
  /**
   * The '<em><b>Font1</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #FONT1_VALUE
   * @generated
   * @ordered
   */
  FONT1(0, "font1", "Arial"),

  /**
   * The '<em><b>Font2</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #FONT2_VALUE
   * @generated
   * @ordered
   */
  FONT2(1, "font2", "Verdana"),

  /**
   * The '<em><b>Font3</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #FONT3_VALUE
   * @generated
   * @ordered
   */
  FONT3(2, "font3", "Times New Roman"),

  /**
   * The '<em><b>Font4</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #FONT4_VALUE
   * @generated
   * @ordered
   */
  FONT4(3, "font4", "sans-serif"),

  /**
   * The '<em><b>Font5</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #FONT5_VALUE
   * @generated
   * @ordered
   */
  FONT5(4, "font5", "Gotham");

  /**
   * The '<em><b>Font1</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #FONT1
   * @model name="font1" literal="Arial"
   * @generated
   * @ordered
   */
  public static final int FONT1_VALUE = 0;

  /**
   * The '<em><b>Font2</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #FONT2
   * @model name="font2" literal="Verdana"
   * @generated
   * @ordered
   */
  public static final int FONT2_VALUE = 1;

  /**
   * The '<em><b>Font3</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #FONT3
   * @model name="font3" literal="Times New Roman"
   * @generated
   * @ordered
   */
  public static final int FONT3_VALUE = 2;

  /**
   * The '<em><b>Font4</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #FONT4
   * @model name="font4" literal="sans-serif"
   * @generated
   * @ordered
   */
  public static final int FONT4_VALUE = 3;

  /**
   * The '<em><b>Font5</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #FONT5
   * @model name="font5" literal="Gotham"
   * @generated
   * @ordered
   */
  public static final int FONT5_VALUE = 4;

  /**
   * An array of all the '<em><b>Font Family</b></em>' enumerators.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private static final Font_Family[] VALUES_ARRAY =
    new Font_Family[]
    {
      FONT1,
      FONT2,
      FONT3,
      FONT4,
      FONT5,
    };

  /**
   * A public read-only list of all the '<em><b>Font Family</b></em>' enumerators.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public static final List<Font_Family> VALUES = Collections.unmodifiableList(Arrays.asList(VALUES_ARRAY));

  /**
   * Returns the '<em><b>Font Family</b></em>' literal with the specified literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param literal the literal.
   * @return the matching enumerator or <code>null</code>.
   * @generated
   */
  public static Font_Family get(String literal)
  {
    for (int i = 0; i < VALUES_ARRAY.length; ++i)
    {
      Font_Family result = VALUES_ARRAY[i];
      if (result.toString().equals(literal))
      {
        return result;
      }
    }
    return null;
  }

  /**
   * Returns the '<em><b>Font Family</b></em>' literal with the specified name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param name the name.
   * @return the matching enumerator or <code>null</code>.
   * @generated
   */
  public static Font_Family getByName(String name)
  {
    for (int i = 0; i < VALUES_ARRAY.length; ++i)
    {
      Font_Family result = VALUES_ARRAY[i];
      if (result.getName().equals(name))
      {
        return result;
      }
    }
    return null;
  }

  /**
   * Returns the '<em><b>Font Family</b></em>' literal with the specified integer value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the integer value.
   * @return the matching enumerator or <code>null</code>.
   * @generated
   */
  public static Font_Family get(int value)
  {
    switch (value)
    {
      case FONT1_VALUE: return FONT1;
      case FONT2_VALUE: return FONT2;
      case FONT3_VALUE: return FONT3;
      case FONT4_VALUE: return FONT4;
      case FONT5_VALUE: return FONT5;
    }
    return null;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private final int value;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private final String name;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private final String literal;

  /**
   * Only this class can construct instances.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private Font_Family(int value, String name, String literal)
  {
    this.value = value;
    this.name = name;
    this.literal = literal;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public int getValue()
  {
    return value;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getName()
  {
    return name;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getLiteral()
  {
    return literal;
  }

  /**
   * Returns the literal value of the enumerator, which is its string representation.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    return literal;
  }
  
} //Font_Family
