/**
 * generated by Xtext 2.19.0
 */
package org.xtext.example.mydsl.iDSL;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Head</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.iDSL.Head#getName <em>Name</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.iDSL.Head#getBgcolor <em>Bgcolor</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.iDSL.Head#getBgpattern <em>Bgpattern</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.iDSL.Head#getBgimage <em>Bgimage</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.iDSL.Head#getSize <em>Size</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.iDSL.Head#getPosition <em>Position</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.iDSL.Head#getLogo <em>Logo</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.iDSL.Head#getTitle <em>Title</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.iDSL.Head#getSubtitle <em>Subtitle</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.iDSL.IDSLPackage#getHead()
 * @model
 * @generated
 */
public interface Head extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see org.xtext.example.mydsl.iDSL.IDSLPackage#getHead_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.iDSL.Head#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Bgcolor</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Bgcolor</em>' containment reference.
   * @see #setBgcolor(Color)
   * @see org.xtext.example.mydsl.iDSL.IDSLPackage#getHead_Bgcolor()
   * @model containment="true"
   * @generated
   */
  Color getBgcolor();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.iDSL.Head#getBgcolor <em>Bgcolor</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Bgcolor</em>' containment reference.
   * @see #getBgcolor()
   * @generated
   */
  void setBgcolor(Color value);

  /**
   * Returns the value of the '<em><b>Bgpattern</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Bgpattern</em>' attribute.
   * @see #setBgpattern(String)
   * @see org.xtext.example.mydsl.iDSL.IDSLPackage#getHead_Bgpattern()
   * @model
   * @generated
   */
  String getBgpattern();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.iDSL.Head#getBgpattern <em>Bgpattern</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Bgpattern</em>' attribute.
   * @see #getBgpattern()
   * @generated
   */
  void setBgpattern(String value);

  /**
   * Returns the value of the '<em><b>Bgimage</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Bgimage</em>' attribute.
   * @see #setBgimage(String)
   * @see org.xtext.example.mydsl.iDSL.IDSLPackage#getHead_Bgimage()
   * @model
   * @generated
   */
  String getBgimage();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.iDSL.Head#getBgimage <em>Bgimage</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Bgimage</em>' attribute.
   * @see #getBgimage()
   * @generated
   */
  void setBgimage(String value);

  /**
   * Returns the value of the '<em><b>Size</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Size</em>' attribute.
   * @see #setSize(String)
   * @see org.xtext.example.mydsl.iDSL.IDSLPackage#getHead_Size()
   * @model
   * @generated
   */
  String getSize();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.iDSL.Head#getSize <em>Size</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Size</em>' attribute.
   * @see #getSize()
   * @generated
   */
  void setSize(String value);

  /**
   * Returns the value of the '<em><b>Position</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Position</em>' attribute.
   * @see #setPosition(String)
   * @see org.xtext.example.mydsl.iDSL.IDSLPackage#getHead_Position()
   * @model
   * @generated
   */
  String getPosition();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.iDSL.Head#getPosition <em>Position</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Position</em>' attribute.
   * @see #getPosition()
   * @generated
   */
  void setPosition(String value);

  /**
   * Returns the value of the '<em><b>Logo</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Logo</em>' containment reference.
   * @see #setLogo(Logo)
   * @see org.xtext.example.mydsl.iDSL.IDSLPackage#getHead_Logo()
   * @model containment="true"
   * @generated
   */
  Logo getLogo();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.iDSL.Head#getLogo <em>Logo</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Logo</em>' containment reference.
   * @see #getLogo()
   * @generated
   */
  void setLogo(Logo value);

  /**
   * Returns the value of the '<em><b>Title</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Title</em>' containment reference.
   * @see #setTitle(Title)
   * @see org.xtext.example.mydsl.iDSL.IDSLPackage#getHead_Title()
   * @model containment="true"
   * @generated
   */
  Title getTitle();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.iDSL.Head#getTitle <em>Title</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Title</em>' containment reference.
   * @see #getTitle()
   * @generated
   */
  void setTitle(Title value);

  /**
   * Returns the value of the '<em><b>Subtitle</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Subtitle</em>' containment reference.
   * @see #setSubtitle(Title)
   * @see org.xtext.example.mydsl.iDSL.IDSLPackage#getHead_Subtitle()
   * @model containment="true"
   * @generated
   */
  Title getSubtitle();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.iDSL.Head#getSubtitle <em>Subtitle</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Subtitle</em>' containment reference.
   * @see #getSubtitle()
   * @generated
   */
  void setSubtitle(Title value);

} // Head
