/**
 * generated by Xtext 2.19.0
 */
package org.xtext.example.mydsl.iDSL;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Infographic Element Type</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.iDSL.InfographicElementType#getType <em>Type</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.iDSL.InfographicElementType#getBgcolor <em>Bgcolor</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.iDSL.InfographicElementType#getBgpattern <em>Bgpattern</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.iDSL.InfographicElementType#getBgimage <em>Bgimage</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.iDSL.InfographicElementType#getBgsize <em>Bgsize</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.iDSL.InfographicElementType#getHead <em>Head</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.iDSL.InfographicElementType#getBoxes <em>Boxes</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.iDSL.InfographicElementType#getTexts <em>Texts</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.iDSL.InfographicElementType#getImages <em>Images</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.iDSL.InfographicElementType#getPiecharts <em>Piecharts</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.iDSL.InfographicElementType#getBarcharts <em>Barcharts</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.iDSL.InfographicElementType#getPicturegraphs <em>Picturegraphs</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.iDSL.InfographicElementType#getFoot <em>Foot</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.iDSL.IDSLPackage#getInfographicElementType()
 * @model
 * @generated
 */
public interface InfographicElementType extends Infographic
{
  /**
   * Returns the value of the '<em><b>Type</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Type</em>' attribute.
   * @see #setType(String)
   * @see org.xtext.example.mydsl.iDSL.IDSLPackage#getInfographicElementType_Type()
   * @model
   * @generated
   */
  String getType();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.iDSL.InfographicElementType#getType <em>Type</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Type</em>' attribute.
   * @see #getType()
   * @generated
   */
  void setType(String value);

  /**
   * Returns the value of the '<em><b>Bgcolor</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Bgcolor</em>' containment reference.
   * @see #setBgcolor(Color)
   * @see org.xtext.example.mydsl.iDSL.IDSLPackage#getInfographicElementType_Bgcolor()
   * @model containment="true"
   * @generated
   */
  Color getBgcolor();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.iDSL.InfographicElementType#getBgcolor <em>Bgcolor</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Bgcolor</em>' containment reference.
   * @see #getBgcolor()
   * @generated
   */
  void setBgcolor(Color value);

  /**
   * Returns the value of the '<em><b>Bgpattern</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Bgpattern</em>' attribute.
   * @see #setBgpattern(String)
   * @see org.xtext.example.mydsl.iDSL.IDSLPackage#getInfographicElementType_Bgpattern()
   * @model
   * @generated
   */
  String getBgpattern();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.iDSL.InfographicElementType#getBgpattern <em>Bgpattern</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Bgpattern</em>' attribute.
   * @see #getBgpattern()
   * @generated
   */
  void setBgpattern(String value);

  /**
   * Returns the value of the '<em><b>Bgimage</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Bgimage</em>' attribute.
   * @see #setBgimage(String)
   * @see org.xtext.example.mydsl.iDSL.IDSLPackage#getInfographicElementType_Bgimage()
   * @model
   * @generated
   */
  String getBgimage();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.iDSL.InfographicElementType#getBgimage <em>Bgimage</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Bgimage</em>' attribute.
   * @see #getBgimage()
   * @generated
   */
  void setBgimage(String value);

  /**
   * Returns the value of the '<em><b>Bgsize</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Bgsize</em>' attribute.
   * @see #setBgsize(String)
   * @see org.xtext.example.mydsl.iDSL.IDSLPackage#getInfographicElementType_Bgsize()
   * @model
   * @generated
   */
  String getBgsize();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.iDSL.InfographicElementType#getBgsize <em>Bgsize</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Bgsize</em>' attribute.
   * @see #getBgsize()
   * @generated
   */
  void setBgsize(String value);

  /**
   * Returns the value of the '<em><b>Head</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Head</em>' containment reference.
   * @see #setHead(Head)
   * @see org.xtext.example.mydsl.iDSL.IDSLPackage#getInfographicElementType_Head()
   * @model containment="true"
   * @generated
   */
  Head getHead();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.iDSL.InfographicElementType#getHead <em>Head</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Head</em>' containment reference.
   * @see #getHead()
   * @generated
   */
  void setHead(Head value);

  /**
   * Returns the value of the '<em><b>Boxes</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.mydsl.iDSL.Box}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Boxes</em>' containment reference list.
   * @see org.xtext.example.mydsl.iDSL.IDSLPackage#getInfographicElementType_Boxes()
   * @model containment="true"
   * @generated
   */
  EList<Box> getBoxes();

  /**
   * Returns the value of the '<em><b>Texts</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.mydsl.iDSL.Text}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Texts</em>' containment reference list.
   * @see org.xtext.example.mydsl.iDSL.IDSLPackage#getInfographicElementType_Texts()
   * @model containment="true"
   * @generated
   */
  EList<Text> getTexts();

  /**
   * Returns the value of the '<em><b>Images</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.mydsl.iDSL.Image}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Images</em>' containment reference list.
   * @see org.xtext.example.mydsl.iDSL.IDSLPackage#getInfographicElementType_Images()
   * @model containment="true"
   * @generated
   */
  EList<Image> getImages();

  /**
   * Returns the value of the '<em><b>Piecharts</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.mydsl.iDSL.Piechart}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Piecharts</em>' containment reference list.
   * @see org.xtext.example.mydsl.iDSL.IDSLPackage#getInfographicElementType_Piecharts()
   * @model containment="true"
   * @generated
   */
  EList<Piechart> getPiecharts();

  /**
   * Returns the value of the '<em><b>Barcharts</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.mydsl.iDSL.Barchart}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Barcharts</em>' containment reference list.
   * @see org.xtext.example.mydsl.iDSL.IDSLPackage#getInfographicElementType_Barcharts()
   * @model containment="true"
   * @generated
   */
  EList<Barchart> getBarcharts();

  /**
   * Returns the value of the '<em><b>Picturegraphs</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.mydsl.iDSL.Picturegraph}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Picturegraphs</em>' containment reference list.
   * @see org.xtext.example.mydsl.iDSL.IDSLPackage#getInfographicElementType_Picturegraphs()
   * @model containment="true"
   * @generated
   */
  EList<Picturegraph> getPicturegraphs();

  /**
   * Returns the value of the '<em><b>Foot</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Foot</em>' containment reference.
   * @see #setFoot(Foot)
   * @see org.xtext.example.mydsl.iDSL.IDSLPackage#getInfographicElementType_Foot()
   * @model containment="true"
   * @generated
   */
  Foot getFoot();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.iDSL.InfographicElementType#getFoot <em>Foot</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Foot</em>' containment reference.
   * @see #getFoot()
   * @generated
   */
  void setFoot(Foot value);

} // InfographicElementType
