/**
 * generated by Xtext 2.19.0
 */
package org.xtext.example.mydsl.iDSL;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Infographic</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.example.mydsl.iDSL.IDSLPackage#getInfographic()
 * @model
 * @generated
 */
public interface Infographic extends EObject
{
} // Infographic
