/**
 * generated by Xtext 2.19.0
 */
package org.xtext.example.mydsl.iDSL;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Picturegraph</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.iDSL.Picturegraph#getName <em>Name</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.iDSL.Picturegraph#getColor <em>Color</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.iDSL.Picturegraph#getColors <em>Colors</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.iDSL.Picturegraph#getPicturegraphdata <em>Picturegraphdata</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.iDSL.Picturegraph#getLabel <em>Label</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.iDSL.Picturegraph#getPadding <em>Padding</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.iDSL.Picturegraph#getPosition <em>Position</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.iDSL.Picturegraph#getShowlegend <em>Showlegend</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.iDSL.Picturegraph#getShowtitle <em>Showtitle</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.iDSL.Picturegraph#getSize <em>Size</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.iDSL.Picturegraph#getTitle <em>Title</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.iDSL.Picturegraph#getType <em>Type</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.iDSL.IDSLPackage#getPicturegraph()
 * @model
 * @generated
 */
public interface Picturegraph extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see org.xtext.example.mydsl.iDSL.IDSLPackage#getPicturegraph_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.iDSL.Picturegraph#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Color</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Color</em>' containment reference.
   * @see #setColor(Color)
   * @see org.xtext.example.mydsl.iDSL.IDSLPackage#getPicturegraph_Color()
   * @model containment="true"
   * @generated
   */
  Color getColor();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.iDSL.Picturegraph#getColor <em>Color</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Color</em>' containment reference.
   * @see #getColor()
   * @generated
   */
  void setColor(Color value);

  /**
   * Returns the value of the '<em><b>Colors</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Colors</em>' attribute.
   * @see #setColors(String)
   * @see org.xtext.example.mydsl.iDSL.IDSLPackage#getPicturegraph_Colors()
   * @model
   * @generated
   */
  String getColors();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.iDSL.Picturegraph#getColors <em>Colors</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Colors</em>' attribute.
   * @see #getColors()
   * @generated
   */
  void setColors(String value);

  /**
   * Returns the value of the '<em><b>Picturegraphdata</b></em>' attribute list.
   * The list contents are of type {@link java.lang.String}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Picturegraphdata</em>' attribute list.
   * @see org.xtext.example.mydsl.iDSL.IDSLPackage#getPicturegraph_Picturegraphdata()
   * @model unique="false"
   * @generated
   */
  EList<String> getPicturegraphdata();

  /**
   * Returns the value of the '<em><b>Label</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Label</em>' attribute.
   * @see #setLabel(String)
   * @see org.xtext.example.mydsl.iDSL.IDSLPackage#getPicturegraph_Label()
   * @model
   * @generated
   */
  String getLabel();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.iDSL.Picturegraph#getLabel <em>Label</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Label</em>' attribute.
   * @see #getLabel()
   * @generated
   */
  void setLabel(String value);

  /**
   * Returns the value of the '<em><b>Padding</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Padding</em>' attribute.
   * @see #setPadding(int)
   * @see org.xtext.example.mydsl.iDSL.IDSLPackage#getPicturegraph_Padding()
   * @model
   * @generated
   */
  int getPadding();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.iDSL.Picturegraph#getPadding <em>Padding</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Padding</em>' attribute.
   * @see #getPadding()
   * @generated
   */
  void setPadding(int value);

  /**
   * Returns the value of the '<em><b>Position</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Position</em>' attribute.
   * @see #setPosition(String)
   * @see org.xtext.example.mydsl.iDSL.IDSLPackage#getPicturegraph_Position()
   * @model
   * @generated
   */
  String getPosition();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.iDSL.Picturegraph#getPosition <em>Position</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Position</em>' attribute.
   * @see #getPosition()
   * @generated
   */
  void setPosition(String value);

  /**
   * Returns the value of the '<em><b>Showlegend</b></em>' attribute.
   * The literals are from the enumeration {@link org.xtext.example.mydsl.iDSL.ShowOptionsOff}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Showlegend</em>' attribute.
   * @see org.xtext.example.mydsl.iDSL.ShowOptionsOff
   * @see #setShowlegend(ShowOptionsOff)
   * @see org.xtext.example.mydsl.iDSL.IDSLPackage#getPicturegraph_Showlegend()
   * @model
   * @generated
   */
  ShowOptionsOff getShowlegend();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.iDSL.Picturegraph#getShowlegend <em>Showlegend</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Showlegend</em>' attribute.
   * @see org.xtext.example.mydsl.iDSL.ShowOptionsOff
   * @see #getShowlegend()
   * @generated
   */
  void setShowlegend(ShowOptionsOff value);

  /**
   * Returns the value of the '<em><b>Showtitle</b></em>' attribute.
   * The literals are from the enumeration {@link org.xtext.example.mydsl.iDSL.ShowOptionsOff}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Showtitle</em>' attribute.
   * @see org.xtext.example.mydsl.iDSL.ShowOptionsOff
   * @see #setShowtitle(ShowOptionsOff)
   * @see org.xtext.example.mydsl.iDSL.IDSLPackage#getPicturegraph_Showtitle()
   * @model
   * @generated
   */
  ShowOptionsOff getShowtitle();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.iDSL.Picturegraph#getShowtitle <em>Showtitle</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Showtitle</em>' attribute.
   * @see org.xtext.example.mydsl.iDSL.ShowOptionsOff
   * @see #getShowtitle()
   * @generated
   */
  void setShowtitle(ShowOptionsOff value);

  /**
   * Returns the value of the '<em><b>Size</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Size</em>' attribute.
   * @see #setSize(String)
   * @see org.xtext.example.mydsl.iDSL.IDSLPackage#getPicturegraph_Size()
   * @model
   * @generated
   */
  String getSize();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.iDSL.Picturegraph#getSize <em>Size</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Size</em>' attribute.
   * @see #getSize()
   * @generated
   */
  void setSize(String value);

  /**
   * Returns the value of the '<em><b>Title</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Title</em>' attribute.
   * @see #setTitle(String)
   * @see org.xtext.example.mydsl.iDSL.IDSLPackage#getPicturegraph_Title()
   * @model
   * @generated
   */
  String getTitle();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.iDSL.Picturegraph#getTitle <em>Title</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Title</em>' attribute.
   * @see #getTitle()
   * @generated
   */
  void setTitle(String value);

  /**
   * Returns the value of the '<em><b>Type</b></em>' attribute.
   * The literals are from the enumeration {@link org.xtext.example.mydsl.iDSL.PicturegraphType}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Type</em>' attribute.
   * @see org.xtext.example.mydsl.iDSL.PicturegraphType
   * @see #setType(PicturegraphType)
   * @see org.xtext.example.mydsl.iDSL.IDSLPackage#getPicturegraph_Type()
   * @model
   * @generated
   */
  PicturegraphType getType();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.iDSL.Picturegraph#getType <em>Type</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Type</em>' attribute.
   * @see org.xtext.example.mydsl.iDSL.PicturegraphType
   * @see #getType()
   * @generated
   */
  void setType(PicturegraphType value);

} // Picturegraph
