/**
 * generated by Xtext 2.19.0
 */
package org.xtext.example.mydsl;

import org.xtext.example.mydsl.IDSLStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class IDSLStandaloneSetup extends IDSLStandaloneSetupGenerated {
  public static void doSetup() {
    new IDSLStandaloneSetup().createInjectorAndDoEMFRegistration();
  }
}
