/*
 * generated by Xtext 2.19.0
 */
package org.xtext.example.mydsl.ide.contentassist.antlr;

import com.google.common.collect.ImmutableMap;
import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.Map;
import org.antlr.runtime.CharStream;
import org.antlr.runtime.TokenSource;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ide.editor.contentassist.antlr.AbstractContentAssistParser;
import org.xtext.example.mydsl.ide.contentassist.antlr.internal.InternalIDSLParser;
import org.xtext.example.mydsl.services.IDSLGrammarAccess;

public class IDSLParser extends AbstractContentAssistParser {

	@Singleton
	public static final class NameMappings {
		
		private final Map<AbstractElement, String> mappings;
		
		@Inject
		public NameMappings(IDSLGrammarAccess grammarAccess) {
			ImmutableMap.Builder<AbstractElement, String> builder = ImmutableMap.builder();
			init(builder, grammarAccess);
			this.mappings = builder.build();
		}
		
		public String getRuleName(AbstractElement element) {
			return mappings.get(element);
		}
		
		private static void init(ImmutableMap.Builder<AbstractElement, String> builder, IDSLGrammarAccess grammarAccess) {
			builder.put(grammarAccess.getInfographicElementTypeAccess().getAlternatives_1(), "rule__InfographicElementType__Alternatives_1");
			builder.put(grammarAccess.getHeadAccess().getAlternatives_2(), "rule__Head__Alternatives_2");
			builder.put(grammarAccess.getHeadAccess().getAlternatives_2_1_0_1_0(), "rule__Head__Alternatives_2_1_0_1_0");
			builder.put(grammarAccess.getTitleAccess().getAlternatives(), "rule__Title__Alternatives");
			builder.put(grammarAccess.getBoxAccess().getAlternatives_3_0(), "rule__Box__Alternatives_3_0");
			builder.put(grammarAccess.getTextAccess().getAlternatives(), "rule__Text__Alternatives");
			builder.put(grammarAccess.getFootAccess().getAlternatives_2(), "rule__Foot__Alternatives_2");
			builder.put(grammarAccess.getFootAccess().getAlternatives_2_1_0_0_1(), "rule__Foot__Alternatives_2_1_0_0_1");
			builder.put(grammarAccess.getColorAccess().getAlternatives(), "rule__Color__Alternatives");
			builder.put(grammarAccess.getPatternAccess().getAlternatives(), "rule__Pattern__Alternatives");
			builder.put(grammarAccess.getColor_BasicAccess().getAlternatives(), "rule__Color_Basic__Alternatives");
			builder.put(grammarAccess.getFont_WeightAccess().getAlternatives(), "rule__Font_Weight__Alternatives");
			builder.put(grammarAccess.getFont_FamilyAccess().getAlternatives(), "rule__Font_Family__Alternatives");
			builder.put(grammarAccess.getAlignPossibilitiesAccess().getAlternatives(), "rule__AlignPossibilities__Alternatives");
			builder.put(grammarAccess.getLegendStyleAccess().getAlternatives(), "rule__LegendStyle__Alternatives");
			builder.put(grammarAccess.getShowOptionsOffAccess().getAlternatives(), "rule__ShowOptionsOff__Alternatives");
			builder.put(grammarAccess.getPieTypeAccess().getAlternatives(), "rule__PieType__Alternatives");
			builder.put(grammarAccess.getBarTypeAccess().getAlternatives(), "rule__BarType__Alternatives");
			builder.put(grammarAccess.getPicturegraphTypeAccess().getAlternatives(), "rule__PicturegraphType__Alternatives");
			builder.put(grammarAccess.getInfographicElementTypeAccess().getGroup_0(), "rule__InfographicElementType__Group_0__0");
			builder.put(grammarAccess.getInfographicElementTypeAccess().getGroup_1_0(), "rule__InfographicElementType__Group_1_0__0");
			builder.put(grammarAccess.getInfographicElementTypeAccess().getGroup_1_1(), "rule__InfographicElementType__Group_1_1__0");
			builder.put(grammarAccess.getInfographicElementTypeAccess().getGroup_1_2(), "rule__InfographicElementType__Group_1_2__0");
			builder.put(grammarAccess.getInfographicElementTypeAccess().getGroup_2(), "rule__InfographicElementType__Group_2__0");
			builder.put(grammarAccess.getHeadAccess().getGroup(), "rule__Head__Group__0");
			builder.put(grammarAccess.getHeadAccess().getGroup_2_1(), "rule__Head__Group_2_1__0");
			builder.put(grammarAccess.getHeadAccess().getGroup_2_1_0(), "rule__Head__Group_2_1_0__0");
			builder.put(grammarAccess.getHeadAccess().getGroup_2_1_0_1_0_0(), "rule__Head__Group_2_1_0_1_0_0__0");
			builder.put(grammarAccess.getHeadAccess().getGroup_2_1_0_1_0_1(), "rule__Head__Group_2_1_0_1_0_1__0");
			builder.put(grammarAccess.getHeadAccess().getGroup_2_1_0_1_0_2(), "rule__Head__Group_2_1_0_1_0_2__0");
			builder.put(grammarAccess.getHeadAccess().getGroup_2_1_0_1_1(), "rule__Head__Group_2_1_0_1_1__0");
			builder.put(grammarAccess.getHeadAccess().getGroup_2_1_0_1_2(), "rule__Head__Group_2_1_0_1_2__0");
			builder.put(grammarAccess.getHeadAccess().getGroup_2_1_0_1_3(), "rule__Head__Group_2_1_0_1_3__0");
			builder.put(grammarAccess.getHeadAccess().getGroup_2_1_0_1_4(), "rule__Head__Group_2_1_0_1_4__0");
			builder.put(grammarAccess.getHeadAccess().getGroup_2_1_0_1_5(), "rule__Head__Group_2_1_0_1_5__0");
			builder.put(grammarAccess.getTitleAccess().getGroup_0(), "rule__Title__Group_0__0");
			builder.put(grammarAccess.getTitleAccess().getGroup_1(), "rule__Title__Group_1__0");
			builder.put(grammarAccess.getTitleAccess().getGroup_1_0(), "rule__Title__Group_1_0__0");
			builder.put(grammarAccess.getTitleAccess().getGroup_1_0_2_0(), "rule__Title__Group_1_0_2_0__0");
			builder.put(grammarAccess.getTitleAccess().getGroup_1_0_2_1(), "rule__Title__Group_1_0_2_1__0");
			builder.put(grammarAccess.getTitleAccess().getGroup_1_0_2_2(), "rule__Title__Group_1_0_2_2__0");
			builder.put(grammarAccess.getTitleAccess().getGroup_1_0_2_3(), "rule__Title__Group_1_0_2_3__0");
			builder.put(grammarAccess.getTitleAccess().getGroup_1_0_2_4(), "rule__Title__Group_1_0_2_4__0");
			builder.put(grammarAccess.getTitleAccess().getGroup_1_0_2_5(), "rule__Title__Group_1_0_2_5__0");
			builder.put(grammarAccess.getLogoAccess().getGroup(), "rule__Logo__Group__0");
			builder.put(grammarAccess.getLogoAccess().getGroup_1_0(), "rule__Logo__Group_1_0__0");
			builder.put(grammarAccess.getLogoAccess().getGroup_1_1(), "rule__Logo__Group_1_1__0");
			builder.put(grammarAccess.getBoxAccess().getGroup(), "rule__Box__Group__0");
			builder.put(grammarAccess.getBoxAccess().getGroup_3_0_0(), "rule__Box__Group_3_0_0__0");
			builder.put(grammarAccess.getBoxAccess().getGroup_3_0_1(), "rule__Box__Group_3_0_1__0");
			builder.put(grammarAccess.getBoxAccess().getGroup_3_0_2(), "rule__Box__Group_3_0_2__0");
			builder.put(grammarAccess.getBoxAccess().getGroup_3_1(), "rule__Box__Group_3_1__0");
			builder.put(grammarAccess.getBoxAccess().getGroup_3_2(), "rule__Box__Group_3_2__0");
			builder.put(grammarAccess.getTextAccess().getGroup_0(), "rule__Text__Group_0__0");
			builder.put(grammarAccess.getTextAccess().getGroup_0_2(), "rule__Text__Group_0_2__0");
			builder.put(grammarAccess.getTextAccess().getGroup_0_2_1_0(), "rule__Text__Group_0_2_1_0__0");
			builder.put(grammarAccess.getTextAccess().getGroup_0_2_1_1(), "rule__Text__Group_0_2_1_1__0");
			builder.put(grammarAccess.getTextAccess().getGroup_0_2_1_2(), "rule__Text__Group_0_2_1_2__0");
			builder.put(grammarAccess.getTextAccess().getGroup_0_2_1_3(), "rule__Text__Group_0_2_1_3__0");
			builder.put(grammarAccess.getTextAccess().getGroup_0_2_1_4(), "rule__Text__Group_0_2_1_4__0");
			builder.put(grammarAccess.getTextAccess().getGroup_0_2_1_5(), "rule__Text__Group_0_2_1_5__0");
			builder.put(grammarAccess.getTextAccess().getGroup_0_2_1_6(), "rule__Text__Group_0_2_1_6__0");
			builder.put(grammarAccess.getTextAccess().getGroup_1(), "rule__Text__Group_1__0");
			builder.put(grammarAccess.getTextAccess().getGroup_1_2(), "rule__Text__Group_1_2__0");
			builder.put(grammarAccess.getTextAccess().getGroup_1_2_1_0(), "rule__Text__Group_1_2_1_0__0");
			builder.put(grammarAccess.getTextAccess().getGroup_1_2_1_1(), "rule__Text__Group_1_2_1_1__0");
			builder.put(grammarAccess.getTextAccess().getGroup_1_2_1_2(), "rule__Text__Group_1_2_1_2__0");
			builder.put(grammarAccess.getTextAccess().getGroup_1_2_1_3(), "rule__Text__Group_1_2_1_3__0");
			builder.put(grammarAccess.getTextAccess().getGroup_1_2_1_4(), "rule__Text__Group_1_2_1_4__0");
			builder.put(grammarAccess.getTextAccess().getGroup_1_2_1_5(), "rule__Text__Group_1_2_1_5__0");
			builder.put(grammarAccess.getImageAccess().getGroup(), "rule__Image__Group__0");
			builder.put(grammarAccess.getImageAccess().getGroup_3_0(), "rule__Image__Group_3_0__0");
			builder.put(grammarAccess.getImageAccess().getGroup_3_1(), "rule__Image__Group_3_1__0");
			builder.put(grammarAccess.getImageAccess().getGroup_3_2(), "rule__Image__Group_3_2__0");
			builder.put(grammarAccess.getPiechartAccess().getGroup(), "rule__Piechart__Group__0");
			builder.put(grammarAccess.getPiechartAccess().getGroup_3_0(), "rule__Piechart__Group_3_0__0");
			builder.put(grammarAccess.getPiechartAccess().getGroup_3_1(), "rule__Piechart__Group_3_1__0");
			builder.put(grammarAccess.getPiechartAccess().getGroup_3_2(), "rule__Piechart__Group_3_2__0");
			builder.put(grammarAccess.getPiechartAccess().getGroup_3_3(), "rule__Piechart__Group_3_3__0");
			builder.put(grammarAccess.getPiechartAccess().getGroup_3_4(), "rule__Piechart__Group_3_4__0");
			builder.put(grammarAccess.getPiechartAccess().getGroup_3_5(), "rule__Piechart__Group_3_5__0");
			builder.put(grammarAccess.getPiechartAccess().getGroup_3_6(), "rule__Piechart__Group_3_6__0");
			builder.put(grammarAccess.getPiechartAccess().getGroup_3_7(), "rule__Piechart__Group_3_7__0");
			builder.put(grammarAccess.getPiechartAccess().getGroup_3_8(), "rule__Piechart__Group_3_8__0");
			builder.put(grammarAccess.getPiechartAccess().getGroup_3_9(), "rule__Piechart__Group_3_9__0");
			builder.put(grammarAccess.getPiechartAccess().getGroup_3_10(), "rule__Piechart__Group_3_10__0");
			builder.put(grammarAccess.getPiechartAccess().getGroup_3_11(), "rule__Piechart__Group_3_11__0");
			builder.put(grammarAccess.getBarchartAccess().getGroup(), "rule__Barchart__Group__0");
			builder.put(grammarAccess.getBarchartAccess().getGroup_3_0(), "rule__Barchart__Group_3_0__0");
			builder.put(grammarAccess.getBarchartAccess().getGroup_3_1(), "rule__Barchart__Group_3_1__0");
			builder.put(grammarAccess.getBarchartAccess().getGroup_3_2(), "rule__Barchart__Group_3_2__0");
			builder.put(grammarAccess.getBarchartAccess().getGroup_3_3(), "rule__Barchart__Group_3_3__0");
			builder.put(grammarAccess.getBarchartAccess().getGroup_3_4(), "rule__Barchart__Group_3_4__0");
			builder.put(grammarAccess.getBarchartAccess().getGroup_3_5(), "rule__Barchart__Group_3_5__0");
			builder.put(grammarAccess.getBarchartAccess().getGroup_3_6(), "rule__Barchart__Group_3_6__0");
			builder.put(grammarAccess.getBarchartAccess().getGroup_3_7(), "rule__Barchart__Group_3_7__0");
			builder.put(grammarAccess.getBarchartAccess().getGroup_3_8(), "rule__Barchart__Group_3_8__0");
			builder.put(grammarAccess.getBarchartAccess().getGroup_3_9(), "rule__Barchart__Group_3_9__0");
			builder.put(grammarAccess.getBarchartAccess().getGroup_3_10(), "rule__Barchart__Group_3_10__0");
			builder.put(grammarAccess.getBarchartAccess().getGroup_3_11(), "rule__Barchart__Group_3_11__0");
			builder.put(grammarAccess.getBarchartAccess().getGroup_3_12(), "rule__Barchart__Group_3_12__0");
			builder.put(grammarAccess.getPicturegraphAccess().getGroup(), "rule__Picturegraph__Group__0");
			builder.put(grammarAccess.getPicturegraphAccess().getGroup_3_0(), "rule__Picturegraph__Group_3_0__0");
			builder.put(grammarAccess.getPicturegraphAccess().getGroup_3_1(), "rule__Picturegraph__Group_3_1__0");
			builder.put(grammarAccess.getPicturegraphAccess().getGroup_3_2(), "rule__Picturegraph__Group_3_2__0");
			builder.put(grammarAccess.getPicturegraphAccess().getGroup_3_3(), "rule__Picturegraph__Group_3_3__0");
			builder.put(grammarAccess.getPicturegraphAccess().getGroup_3_4(), "rule__Picturegraph__Group_3_4__0");
			builder.put(grammarAccess.getPicturegraphAccess().getGroup_3_5(), "rule__Picturegraph__Group_3_5__0");
			builder.put(grammarAccess.getPicturegraphAccess().getGroup_3_6(), "rule__Picturegraph__Group_3_6__0");
			builder.put(grammarAccess.getPicturegraphAccess().getGroup_3_7(), "rule__Picturegraph__Group_3_7__0");
			builder.put(grammarAccess.getPicturegraphAccess().getGroup_3_8(), "rule__Picturegraph__Group_3_8__0");
			builder.put(grammarAccess.getPicturegraphAccess().getGroup_3_9(), "rule__Picturegraph__Group_3_9__0");
			builder.put(grammarAccess.getPicturegraphAccess().getGroup_3_10(), "rule__Picturegraph__Group_3_10__0");
			builder.put(grammarAccess.getFootAccess().getGroup(), "rule__Foot__Group__0");
			builder.put(grammarAccess.getFootAccess().getGroup_2_1(), "rule__Foot__Group_2_1__0");
			builder.put(grammarAccess.getFootAccess().getGroup_2_1_0_0(), "rule__Foot__Group_2_1_0_0__0");
			builder.put(grammarAccess.getFootAccess().getGroup_2_1_0_0_1_0(), "rule__Foot__Group_2_1_0_0_1_0__0");
			builder.put(grammarAccess.getFootAccess().getGroup_2_1_0_0_1_1(), "rule__Foot__Group_2_1_0_0_1_1__0");
			builder.put(grammarAccess.getFootAccess().getGroup_2_1_0_0_1_2(), "rule__Foot__Group_2_1_0_0_1_2__0");
			builder.put(grammarAccess.getFootAccess().getGroup_2_1_0_1(), "rule__Foot__Group_2_1_0_1__0");
			builder.put(grammarAccess.getFootAccess().getGroup_2_1_0_2(), "rule__Foot__Group_2_1_0_2__0");
			builder.put(grammarAccess.getFootAccess().getGroup_2_1_0_3(), "rule__Foot__Group_2_1_0_3__0");
			builder.put(grammarAccess.getColorAccess().getGroup_0(), "rule__Color__Group_0__0");
			builder.put(grammarAccess.getColorAccess().getGroup_1(), "rule__Color__Group_1__0");
			builder.put(grammarAccess.getFONTAccess().getGroup(), "rule__FONT__Group__0");
			builder.put(grammarAccess.getChartDataAccess().getGroup(), "rule__ChartData__Group__0");
			builder.put(grammarAccess.getInfographicElementTypeAccess().getTypeAssignment_0_2(), "rule__InfographicElementType__TypeAssignment_0_2");
			builder.put(grammarAccess.getInfographicElementTypeAccess().getBgcolorAssignment_1_0_2(), "rule__InfographicElementType__BgcolorAssignment_1_0_2");
			builder.put(grammarAccess.getInfographicElementTypeAccess().getBgpatternAssignment_1_1_2(), "rule__InfographicElementType__BgpatternAssignment_1_1_2");
			builder.put(grammarAccess.getInfographicElementTypeAccess().getBgimageAssignment_1_2_2(), "rule__InfographicElementType__BgimageAssignment_1_2_2");
			builder.put(grammarAccess.getInfographicElementTypeAccess().getBgsizeAssignment_2_2(), "rule__InfographicElementType__BgsizeAssignment_2_2");
			builder.put(grammarAccess.getInfographicElementTypeAccess().getHeadAssignment_3(), "rule__InfographicElementType__HeadAssignment_3");
			builder.put(grammarAccess.getInfographicElementTypeAccess().getBoxesAssignment_4(), "rule__InfographicElementType__BoxesAssignment_4");
			builder.put(grammarAccess.getInfographicElementTypeAccess().getTextsAssignment_5(), "rule__InfographicElementType__TextsAssignment_5");
			builder.put(grammarAccess.getInfographicElementTypeAccess().getImagesAssignment_6(), "rule__InfographicElementType__ImagesAssignment_6");
			builder.put(grammarAccess.getInfographicElementTypeAccess().getPiechartsAssignment_7(), "rule__InfographicElementType__PiechartsAssignment_7");
			builder.put(grammarAccess.getInfographicElementTypeAccess().getBarchartsAssignment_8(), "rule__InfographicElementType__BarchartsAssignment_8");
			builder.put(grammarAccess.getInfographicElementTypeAccess().getPicturegraphsAssignment_9(), "rule__InfographicElementType__PicturegraphsAssignment_9");
			builder.put(grammarAccess.getInfographicElementTypeAccess().getFootAssignment_10(), "rule__InfographicElementType__FootAssignment_10");
			builder.put(grammarAccess.getHeadAccess().getNameAssignment_0(), "rule__Head__NameAssignment_0");
			builder.put(grammarAccess.getHeadAccess().getBgcolorAssignment_2_1_0_1_0_0_2(), "rule__Head__BgcolorAssignment_2_1_0_1_0_0_2");
			builder.put(grammarAccess.getHeadAccess().getBgpatternAssignment_2_1_0_1_0_1_2(), "rule__Head__BgpatternAssignment_2_1_0_1_0_1_2");
			builder.put(grammarAccess.getHeadAccess().getBgimageAssignment_2_1_0_1_0_2_2(), "rule__Head__BgimageAssignment_2_1_0_1_0_2_2");
			builder.put(grammarAccess.getHeadAccess().getSizeAssignment_2_1_0_1_1_2(), "rule__Head__SizeAssignment_2_1_0_1_1_2");
			builder.put(grammarAccess.getHeadAccess().getPositionAssignment_2_1_0_1_2_2(), "rule__Head__PositionAssignment_2_1_0_1_2_2");
			builder.put(grammarAccess.getHeadAccess().getLogoAssignment_2_1_0_1_3_2(), "rule__Head__LogoAssignment_2_1_0_1_3_2");
			builder.put(grammarAccess.getHeadAccess().getTitleAssignment_2_1_0_1_4_2(), "rule__Head__TitleAssignment_2_1_0_1_4_2");
			builder.put(grammarAccess.getHeadAccess().getSubtitleAssignment_2_1_0_1_5_2(), "rule__Head__SubtitleAssignment_2_1_0_1_5_2");
			builder.put(grammarAccess.getTitleAccess().getAlignAssignment_1_0_2_0_2(), "rule__Title__AlignAssignment_1_0_2_0_2");
			builder.put(grammarAccess.getTitleAccess().getColorAssignment_1_0_2_1_2(), "rule__Title__ColorAssignment_1_0_2_1_2");
			builder.put(grammarAccess.getTitleAccess().getFontAssignment_1_0_2_2_2(), "rule__Title__FontAssignment_1_0_2_2_2");
			builder.put(grammarAccess.getTitleAccess().getPositionAssignment_1_0_2_3_2(), "rule__Title__PositionAssignment_1_0_2_3_2");
			builder.put(grammarAccess.getTitleAccess().getMaxwidthAssignment_1_0_2_4_2(), "rule__Title__MaxwidthAssignment_1_0_2_4_2");
			builder.put(grammarAccess.getTitleAccess().getValueAssignment_1_0_2_5_2(), "rule__Title__ValueAssignment_1_0_2_5_2");
			builder.put(grammarAccess.getLogoAccess().getSizeAssignment_1_0_2(), "rule__Logo__SizeAssignment_1_0_2");
			builder.put(grammarAccess.getLogoAccess().getPositionAssignment_1_1_2(), "rule__Logo__PositionAssignment_1_1_2");
			builder.put(grammarAccess.getBoxAccess().getNameAssignment_0(), "rule__Box__NameAssignment_0");
			builder.put(grammarAccess.getBoxAccess().getBgcolorAssignment_3_0_0_2(), "rule__Box__BgcolorAssignment_3_0_0_2");
			builder.put(grammarAccess.getBoxAccess().getBgpatternAssignment_3_0_1_2(), "rule__Box__BgpatternAssignment_3_0_1_2");
			builder.put(grammarAccess.getBoxAccess().getBgimageAssignment_3_0_2_2(), "rule__Box__BgimageAssignment_3_0_2_2");
			builder.put(grammarAccess.getBoxAccess().getSizeAssignment_3_1_2(), "rule__Box__SizeAssignment_3_1_2");
			builder.put(grammarAccess.getBoxAccess().getPositionAssignment_3_2_2(), "rule__Box__PositionAssignment_3_2_2");
			builder.put(grammarAccess.getTextAccess().getNameAssignment_0_0(), "rule__Text__NameAssignment_0_0");
			builder.put(grammarAccess.getTextAccess().getAlignAssignment_0_2_1_0_2(), "rule__Text__AlignAssignment_0_2_1_0_2");
			builder.put(grammarAccess.getTextAccess().getColorAssignment_0_2_1_1_2(), "rule__Text__ColorAssignment_0_2_1_1_2");
			builder.put(grammarAccess.getTextAccess().getFontAssignment_0_2_1_2_2(), "rule__Text__FontAssignment_0_2_1_2_2");
			builder.put(grammarAccess.getTextAccess().getLineheightAssignment_0_2_1_3_2(), "rule__Text__LineheightAssignment_0_2_1_3_2");
			builder.put(grammarAccess.getTextAccess().getPositionAssignment_0_2_1_4_2(), "rule__Text__PositionAssignment_0_2_1_4_2");
			builder.put(grammarAccess.getTextAccess().getMaxwidthAssignment_0_2_1_5_2(), "rule__Text__MaxwidthAssignment_0_2_1_5_2");
			builder.put(grammarAccess.getTextAccess().getValueAssignment_0_2_1_6_2(), "rule__Text__ValueAssignment_0_2_1_6_2");
			builder.put(grammarAccess.getTextAccess().getNameAssignment_1_0(), "rule__Text__NameAssignment_1_0");
			builder.put(grammarAccess.getTextAccess().getAlignAssignment_1_2_1_0_2(), "rule__Text__AlignAssignment_1_2_1_0_2");
			builder.put(grammarAccess.getTextAccess().getColorAssignment_1_2_1_1_2(), "rule__Text__ColorAssignment_1_2_1_1_2");
			builder.put(grammarAccess.getTextAccess().getFontAssignment_1_2_1_2_2(), "rule__Text__FontAssignment_1_2_1_2_2");
			builder.put(grammarAccess.getTextAccess().getPositionAssignment_1_2_1_3_2(), "rule__Text__PositionAssignment_1_2_1_3_2");
			builder.put(grammarAccess.getTextAccess().getMaxwidthAssignment_1_2_1_4_2(), "rule__Text__MaxwidthAssignment_1_2_1_4_2");
			builder.put(grammarAccess.getTextAccess().getValueAssignment_1_2_1_5_2(), "rule__Text__ValueAssignment_1_2_1_5_2");
			builder.put(grammarAccess.getImageAccess().getNameAssignment_0(), "rule__Image__NameAssignment_0");
			builder.put(grammarAccess.getImageAccess().getPositionAssignment_3_0_2(), "rule__Image__PositionAssignment_3_0_2");
			builder.put(grammarAccess.getImageAccess().getSizeAssignment_3_1_2(), "rule__Image__SizeAssignment_3_1_2");
			builder.put(grammarAccess.getImageAccess().getSrcAssignment_3_2_2(), "rule__Image__SrcAssignment_3_2_2");
			builder.put(grammarAccess.getPiechartAccess().getNameAssignment_0(), "rule__Piechart__NameAssignment_0");
			builder.put(grammarAccess.getPiechartAccess().getColorAssignment_3_0_2(), "rule__Piechart__ColorAssignment_3_0_2");
			builder.put(grammarAccess.getPiechartAccess().getColorsAssignment_3_1_2(), "rule__Piechart__ColorsAssignment_3_1_2");
			builder.put(grammarAccess.getPiechartAccess().getPiedataAssignment_3_2_4(), "rule__Piechart__PiedataAssignment_3_2_4");
			builder.put(grammarAccess.getPiechartAccess().getLegendstyleAssignment_3_3_2(), "rule__Piechart__LegendstyleAssignment_3_3_2");
			builder.put(grammarAccess.getPiechartAccess().getPaddingAssignment_3_4_2(), "rule__Piechart__PaddingAssignment_3_4_2");
			builder.put(grammarAccess.getPiechartAccess().getPositionAssignment_3_5_2(), "rule__Piechart__PositionAssignment_3_5_2");
			builder.put(grammarAccess.getPiechartAccess().getShowlegendAssignment_3_6_2(), "rule__Piechart__ShowlegendAssignment_3_6_2");
			builder.put(grammarAccess.getPiechartAccess().getShowtitleAssignment_3_7_2(), "rule__Piechart__ShowtitleAssignment_3_7_2");
			builder.put(grammarAccess.getPiechartAccess().getShowpercentageAssignment_3_8_2(), "rule__Piechart__ShowpercentageAssignment_3_8_2");
			builder.put(grammarAccess.getPiechartAccess().getSizeAssignment_3_9_2(), "rule__Piechart__SizeAssignment_3_9_2");
			builder.put(grammarAccess.getPiechartAccess().getTitleAssignment_3_10_2(), "rule__Piechart__TitleAssignment_3_10_2");
			builder.put(grammarAccess.getPiechartAccess().getTypeAssignment_3_11_2(), "rule__Piechart__TypeAssignment_3_11_2");
			builder.put(grammarAccess.getBarchartAccess().getNameAssignment_0(), "rule__Barchart__NameAssignment_0");
			builder.put(grammarAccess.getBarchartAccess().getColorAssignment_3_0_2(), "rule__Barchart__ColorAssignment_3_0_2");
			builder.put(grammarAccess.getBarchartAccess().getColorsAssignment_3_1_2(), "rule__Barchart__ColorsAssignment_3_1_2");
			builder.put(grammarAccess.getBarchartAccess().getBardataAssignment_3_2_4(), "rule__Barchart__BardataAssignment_3_2_4");
			builder.put(grammarAccess.getBarchartAccess().getGridscaleAssignment_3_3_2(), "rule__Barchart__GridscaleAssignment_3_3_2");
			builder.put(grammarAccess.getBarchartAccess().getLegendstyleAssignment_3_4_2(), "rule__Barchart__LegendstyleAssignment_3_4_2");
			builder.put(grammarAccess.getBarchartAccess().getPaddingAssignment_3_5_2(), "rule__Barchart__PaddingAssignment_3_5_2");
			builder.put(grammarAccess.getBarchartAccess().getPositionAssignment_3_6_2(), "rule__Barchart__PositionAssignment_3_6_2");
			builder.put(grammarAccess.getBarchartAccess().getShowgridAssignment_3_7_2(), "rule__Barchart__ShowgridAssignment_3_7_2");
			builder.put(grammarAccess.getBarchartAccess().getShowlegendAssignment_3_8_2(), "rule__Barchart__ShowlegendAssignment_3_8_2");
			builder.put(grammarAccess.getBarchartAccess().getShowtitleAssignment_3_9_2(), "rule__Barchart__ShowtitleAssignment_3_9_2");
			builder.put(grammarAccess.getBarchartAccess().getSizeAssignment_3_10_2(), "rule__Barchart__SizeAssignment_3_10_2");
			builder.put(grammarAccess.getBarchartAccess().getTitleAssignment_3_11_2(), "rule__Barchart__TitleAssignment_3_11_2");
			builder.put(grammarAccess.getBarchartAccess().getTypeAssignment_3_12_2(), "rule__Barchart__TypeAssignment_3_12_2");
			builder.put(grammarAccess.getPicturegraphAccess().getNameAssignment_0(), "rule__Picturegraph__NameAssignment_0");
			builder.put(grammarAccess.getPicturegraphAccess().getColorAssignment_3_0_2(), "rule__Picturegraph__ColorAssignment_3_0_2");
			builder.put(grammarAccess.getPicturegraphAccess().getColorsAssignment_3_1_2(), "rule__Picturegraph__ColorsAssignment_3_1_2");
			builder.put(grammarAccess.getPicturegraphAccess().getPicturegraphdataAssignment_3_2_4(), "rule__Picturegraph__PicturegraphdataAssignment_3_2_4");
			builder.put(grammarAccess.getPicturegraphAccess().getLabelAssignment_3_3_2(), "rule__Picturegraph__LabelAssignment_3_3_2");
			builder.put(grammarAccess.getPicturegraphAccess().getPaddingAssignment_3_4_2(), "rule__Picturegraph__PaddingAssignment_3_4_2");
			builder.put(grammarAccess.getPicturegraphAccess().getPositionAssignment_3_5_2(), "rule__Picturegraph__PositionAssignment_3_5_2");
			builder.put(grammarAccess.getPicturegraphAccess().getShowlegendAssignment_3_6_2(), "rule__Picturegraph__ShowlegendAssignment_3_6_2");
			builder.put(grammarAccess.getPicturegraphAccess().getShowtitleAssignment_3_7_2(), "rule__Picturegraph__ShowtitleAssignment_3_7_2");
			builder.put(grammarAccess.getPicturegraphAccess().getSizeAssignment_3_8_2(), "rule__Picturegraph__SizeAssignment_3_8_2");
			builder.put(grammarAccess.getPicturegraphAccess().getTitleAssignment_3_9_2(), "rule__Picturegraph__TitleAssignment_3_9_2");
			builder.put(grammarAccess.getPicturegraphAccess().getTypeAssignment_3_10_2(), "rule__Picturegraph__TypeAssignment_3_10_2");
			builder.put(grammarAccess.getFootAccess().getNameAssignment_0(), "rule__Foot__NameAssignment_0");
			builder.put(grammarAccess.getFootAccess().getBgcolorAssignment_2_1_0_0_1_0_2(), "rule__Foot__BgcolorAssignment_2_1_0_0_1_0_2");
			builder.put(grammarAccess.getFootAccess().getBgpatternAssignment_2_1_0_0_1_1_2(), "rule__Foot__BgpatternAssignment_2_1_0_0_1_1_2");
			builder.put(grammarAccess.getFootAccess().getBgimageAssignment_2_1_0_0_1_2_2(), "rule__Foot__BgimageAssignment_2_1_0_0_1_2_2");
			builder.put(grammarAccess.getFootAccess().getPositionAssignment_2_1_0_1_2(), "rule__Foot__PositionAssignment_2_1_0_1_2");
			builder.put(grammarAccess.getFootAccess().getSizeAssignment_2_1_0_2_2(), "rule__Foot__SizeAssignment_2_1_0_2_2");
			builder.put(grammarAccess.getFootAccess().getTextAssignment_2_1_0_3_2(), "rule__Foot__TextAssignment_2_1_0_3_2");
			builder.put(grammarAccess.getColorAccess().getColorAssignment_0_1(), "rule__Color__ColorAssignment_0_1");
			builder.put(grammarAccess.getFONTAccess().getWeightAssignment_0(), "rule__FONT__WeightAssignment_0");
			builder.put(grammarAccess.getFONTAccess().getFamilyAssignment_2(), "rule__FONT__FamilyAssignment_2");
			builder.put(grammarAccess.getInfographicElementTypeAccess().getUnorderedGroup(), "rule__InfographicElementType__UnorderedGroup");
			builder.put(grammarAccess.getHeadAccess().getUnorderedGroup_2_1_0_1(), "rule__Head__UnorderedGroup_2_1_0_1");
			builder.put(grammarAccess.getTitleAccess().getUnorderedGroup_1_0_2(), "rule__Title__UnorderedGroup_1_0_2");
			builder.put(grammarAccess.getLogoAccess().getUnorderedGroup_1(), "rule__Logo__UnorderedGroup_1");
			builder.put(grammarAccess.getBoxAccess().getUnorderedGroup_3(), "rule__Box__UnorderedGroup_3");
			builder.put(grammarAccess.getTextAccess().getUnorderedGroup_0_2_1(), "rule__Text__UnorderedGroup_0_2_1");
			builder.put(grammarAccess.getTextAccess().getUnorderedGroup_1_2_1(), "rule__Text__UnorderedGroup_1_2_1");
			builder.put(grammarAccess.getImageAccess().getUnorderedGroup_3(), "rule__Image__UnorderedGroup_3");
			builder.put(grammarAccess.getPiechartAccess().getUnorderedGroup_3(), "rule__Piechart__UnorderedGroup_3");
			builder.put(grammarAccess.getBarchartAccess().getUnorderedGroup_3(), "rule__Barchart__UnorderedGroup_3");
			builder.put(grammarAccess.getPicturegraphAccess().getUnorderedGroup_3(), "rule__Picturegraph__UnorderedGroup_3");
			builder.put(grammarAccess.getFootAccess().getUnorderedGroup_2_1_0(), "rule__Foot__UnorderedGroup_2_1_0");
		}
	}
	
	@Inject
	private NameMappings nameMappings;

	@Inject
	private IDSLGrammarAccess grammarAccess;

	@Override
	protected InternalIDSLParser createParser() {
		InternalIDSLParser result = new InternalIDSLParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}

	@Override
	protected TokenSource createLexer(CharStream stream) {
		return new IDSLTokenSource(super.createLexer(stream));
	}
	
	@Override
	protected String getRuleName(AbstractElement element) {
		return nameMappings.getRuleName(element);
	}

	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}

	public IDSLGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(IDSLGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
	public NameMappings getNameMappings() {
		return nameMappings;
	}
	
	public void setNameMappings(NameMappings nameMappings) {
		this.nameMappings = nameMappings;
	}
}
